/** Static texts used inside generated PDFs (kept out of messages/*.json: they are legal artefacts). */
export type PdfLocale = "es" | "en";

export const PDF_LABELS = {
  es: {
    footer: (code: string, host: string) =>
      `DocuFirma · Código de verificación ${code} · ${host}/verificar`,
    signaturePage: "Página de firmas",
    evidenceSummary: "Resumen del certificado de evidencias",
    evidenceTitle: "Certificado de evidencias",
    envelope: "Sobre",
    title: "Título",
    code: "Código de verificación",
    sender: "Remitente",
    created: "Creado",
    sent: "Enviado",
    completed: "Completado",
    documents: "Documentos",
    pages: "págs.",
    originalHash: "SHA-256 original",
    signedHash: "SHA-256 del PDF firmado",
    signers: "Firmantes",
    signer: "Firmante",
    signedAt: "Firmado",
    signerId: "ID del firmante",
    email: "Email",
    ip: "Dirección IP",
    location: "Ubicación aproximada",
    device: "Dispositivo",
    userAgent: "Agente de usuario",
    screen: "Pantalla",
    timezone: "Zona horaria",
    pointer: "Tipo de puntero",
    pressure: "Presión soportada",
    strokes: "Trazos / puntos / duración",
    biometricHash: "SHA-256 datos biométricos",
    consent: "Consentimiento",
    timeline: "Cronología de eventos",
    yes: "Sí",
    no: "No",
    verifyAt: "Verifica este documento en",
    scan: "Escanea para verificar",
    legalTitle: "Validez legal",
    legal:
      "Este documento ha sido firmado mediante firma electrónica avanzada conforme al artículo 26 del Reglamento (UE) 910/2014 (eIDAS): la firma está vinculada al firmante de manera única mediante un enlace personal enviado a su email, permite su identificación, ha sido creada con datos bajo su control exclusivo (trazo biométrico con presión, velocidad y tiempos) y cualquier modificación posterior es detectable gracias a la huella SHA-256 del documento. El documento firmado y este certificado se sellan con un sello de tiempo cualificado conforme a los artículos 41 y 42 del Reglamento eIDAS (RFC 3161).",
    tsaNote:
      "El sello de tiempo RFC 3161 (.tsr) de este PDF se puede descargar y verificar en la página de verificación.",
    page: (n: number, total: number) => `Página ${n} de ${total}`,
    generated: "Generado por DocuFirma",
  },
  en: {
    footer: (code: string, host: string) =>
      `DocuFirma · Verification code ${code} · ${host}/verify`,
    signaturePage: "Signature page",
    evidenceSummary: "Evidence certificate summary",
    evidenceTitle: "Evidence certificate",
    envelope: "Envelope",
    title: "Title",
    code: "Verification code",
    sender: "Sender",
    created: "Created",
    sent: "Sent",
    completed: "Completed",
    documents: "Documents",
    pages: "pages",
    originalHash: "Original SHA-256",
    signedHash: "Signed PDF SHA-256",
    signers: "Signers",
    signer: "Signer",
    signedAt: "Signed",
    signerId: "Signer ID",
    email: "Email",
    ip: "IP address",
    location: "Approximate location",
    device: "Device",
    userAgent: "User agent",
    screen: "Screen",
    timezone: "Time zone",
    pointer: "Pointer type",
    pressure: "Pressure supported",
    strokes: "Strokes / points / duration",
    biometricHash: "Biometric data SHA-256",
    consent: "Consent",
    timeline: "Event timeline",
    yes: "Yes",
    no: "No",
    verifyAt: "Verify this document at",
    scan: "Scan to verify",
    legalTitle: "Legal validity",
    legal:
      "This document has been signed with an advanced electronic signature under Article 26 of Regulation (EU) 910/2014 (eIDAS): the signature is uniquely linked to the signer through a personal link sent to their email, is capable of identifying them, was created using data under their sole control (biometric stroke with pressure, speed and timing) and any subsequent change is detectable thanks to the document's SHA-256 fingerprint. The signed document and this certificate are sealed with a qualified timestamp under Articles 41 and 42 of the eIDAS Regulation (RFC 3161).",
    tsaNote:
      "The RFC 3161 timestamp (.tsr) of this PDF can be downloaded and verified on the verification page.",
    page: (n: number, total: number) => `Page ${n} of ${total}`,
    generated: "Generated by DocuFirma",
  },
} as const;

export const EVENT_LABELS: Record<PdfLocale, Record<string, string>> = {
  es: {
    created: "Envío creado",
    sent: "Envío enviado",
    email_sent: "Email enviado",
    email_delivered: "Email entregado",
    email_failed: "Email no entregado",
    opened: "Enlace abierto",
    document_viewed: "Documento visto",
    scrolled_to_end: "Documento leído hasta el final",
    consent_accepted: "Consentimiento aceptado",
    signed: "Firmado",
    declined: "Rechazado",
    reminder_sent: "Recordatorio enviado",
    completed: "Sobre completado",
    expired: "Caducado",
    canceled: "Cancelado",
    tsa_granted: "Sello de tiempo aplicado",
    tsa_failed: "Error de sellado (reintento)",
    downloaded: "Descarga",
  },
  en: {
    created: "Envelope created",
    sent: "Envelope sent",
    email_sent: "Email sent",
    email_delivered: "Email delivered",
    email_failed: "Email failed",
    opened: "Link opened",
    document_viewed: "Document viewed",
    scrolled_to_end: "Document read to the end",
    consent_accepted: "Consent accepted",
    signed: "Signed",
    declined: "Declined",
    reminder_sent: "Reminder sent",
    completed: "Envelope completed",
    expired: "Expired",
    canceled: "Canceled",
    tsa_granted: "Timestamp applied",
    tsa_failed: "Timestamping failed (retry)",
    downloaded: "Download",
  },
};

export function formatUtc(iso: string | Date | null | undefined) {
  if (!iso) return "—";
  return `${new Date(iso)
    .toISOString()
    .replace("T", " ")
    .replace(/\.\d{3}Z$/, "")} UTC`;
}

export function formatLocal(
  iso: string | Date | null | undefined,
  locale: PdfLocale,
  timeZone = "Europe/Madrid",
) {
  if (!iso) return "—";
  try {
    return new Intl.DateTimeFormat(locale === "en" ? "en-GB" : "es-ES", {
      day: "2-digit",
      month: "short",
      year: "numeric",
      hour: "2-digit",
      minute: "2-digit",
      second: "2-digit",
      timeZone,
      timeZoneName: "short",
    }).format(new Date(iso));
  } catch {
    return formatUtc(iso);
  }
}
