// Generated by scripts/gen-db-types.ts from supabase/migrations — do not edit by hand.
// Equivalent to `supabase gen types typescript --schema public`.

export type Json = string | number | boolean | null | { [key: string]: Json | undefined } | Json[];

export type Database = {
  __InternalSupabase: { PostgrestVersion: "13" };
  public: {
    Tables: {
      app_settings: {
        Row: {
          key: string;
          updated_at: string;
          value: Json;
        };
        Insert: {
          key: string;
          updated_at?: string;
          value: Json;
        };
        Update: {
          key?: string;
          updated_at?: string;
          value?: Json;
        };
        Relationships: [
        ];
      };
      contacts: {
        Row: {
          created_at: string;
          email: string;
          first_name: string;
          id: string;
          last_name: string;
          last_used_at: string | null;
          updated_at: string;
          user_id: string;
        };
        Insert: {
          created_at?: string;
          email: string;
          first_name: string;
          id?: string;
          last_name: string;
          last_used_at?: string | null;
          updated_at?: string;
          user_id?: string;
        };
        Update: {
          created_at?: string;
          email?: string;
          first_name?: string;
          id?: string;
          last_name?: string;
          last_used_at?: string | null;
          updated_at?: string;
          user_id?: string;
        };
        Relationships: [
          {
            foreignKeyName: "contacts_user_id_fkey";
            columns: ["user_id"];
            isOneToOne: false;
            referencedRelation: "profiles";
            referencedColumns: ["id"];
          },
        ];
      };
      credit_ledger: {
        Row: {
          amount: number;
          created_at: string;
          envelope_id: string | null;
          expires_at: string | null;
          id: string;
          kind: Database["public"]["Enums"]["credit_kind"];
          note: string | null;
          pack_id: string | null;
          pool: Database["public"]["Enums"]["credit_pool"];
          signer_id: string | null;
          stripe_invoice_id: string | null;
          stripe_payment_intent_id: string | null;
          user_id: string;
        };
        Insert: {
          amount: number;
          created_at?: string;
          envelope_id?: string | null;
          expires_at?: string | null;
          id?: string;
          kind: Database["public"]["Enums"]["credit_kind"];
          note?: string | null;
          pack_id?: string | null;
          pool: Database["public"]["Enums"]["credit_pool"];
          signer_id?: string | null;
          stripe_invoice_id?: string | null;
          stripe_payment_intent_id?: string | null;
          user_id: string;
        };
        Update: {
          amount?: number;
          created_at?: string;
          envelope_id?: string | null;
          expires_at?: string | null;
          id?: string;
          kind?: Database["public"]["Enums"]["credit_kind"];
          note?: string | null;
          pack_id?: string | null;
          pool?: Database["public"]["Enums"]["credit_pool"];
          signer_id?: string | null;
          stripe_invoice_id?: string | null;
          stripe_payment_intent_id?: string | null;
          user_id?: string;
        };
        Relationships: [
          {
            foreignKeyName: "credit_ledger_envelope_id_fkey";
            columns: ["envelope_id"];
            isOneToOne: false;
            referencedRelation: "envelopes";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "credit_ledger_pack_id_fkey";
            columns: ["pack_id"];
            isOneToOne: false;
            referencedRelation: "credit_packs";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "credit_ledger_signer_id_fkey";
            columns: ["signer_id"];
            isOneToOne: false;
            referencedRelation: "signers";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "credit_ledger_user_id_fkey";
            columns: ["user_id"];
            isOneToOne: false;
            referencedRelation: "profiles";
            referencedColumns: ["id"];
          },
        ];
      };
      credit_packs: {
        Row: {
          active: boolean;
          created_at: string;
          credits: number;
          currency: string;
          id: string;
          name_en: string;
          name_es: string;
          price_cents: number;
          slug: string;
          sort_order: number;
          stripe_price_id: string | null;
          updated_at: string;
        };
        Insert: {
          active?: boolean;
          created_at?: string;
          credits: number;
          currency?: string;
          id?: string;
          name_en: string;
          name_es: string;
          price_cents: number;
          slug: string;
          sort_order?: number;
          stripe_price_id?: string | null;
          updated_at?: string;
        };
        Update: {
          active?: boolean;
          created_at?: string;
          credits?: number;
          currency?: string;
          id?: string;
          name_en?: string;
          name_es?: string;
          price_cents?: number;
          slug?: string;
          sort_order?: number;
          stripe_price_id?: string | null;
          updated_at?: string;
        };
        Relationships: [
        ];
      };
      deleted_accounts: {
        Row: {
          deleted_at: string;
          email_sha256: string;
          id: string;
          stripe_customer_id: string | null;
          user_id: string;
        };
        Insert: {
          deleted_at?: string;
          email_sha256: string;
          id?: string;
          stripe_customer_id?: string | null;
          user_id: string;
        };
        Update: {
          deleted_at?: string;
          email_sha256?: string;
          id?: string;
          stripe_customer_id?: string | null;
          user_id?: string;
        };
        Relationships: [
        ];
      };
      documents: {
        Row: {
          created_at: string;
          envelope_id: string;
          id: string;
          mime_type: string;
          name: string;
          order_index: number;
          original_path: string;
          original_sha256: string;
          page_count: number;
          size_bytes: number;
          source_mime_type: string | null;
          updated_at: string;
        };
        Insert: {
          created_at?: string;
          envelope_id: string;
          id?: string;
          mime_type?: string;
          name: string;
          order_index?: number;
          original_path: string;
          original_sha256: string;
          page_count: number;
          size_bytes: number;
          source_mime_type?: string | null;
          updated_at?: string;
        };
        Update: {
          created_at?: string;
          envelope_id?: string;
          id?: string;
          mime_type?: string;
          name?: string;
          order_index?: number;
          original_path?: string;
          original_sha256?: string;
          page_count?: number;
          size_bytes?: number;
          source_mime_type?: string | null;
          updated_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: "documents_envelope_id_fkey";
            columns: ["envelope_id"];
            isOneToOne: false;
            referencedRelation: "envelopes";
            referencedColumns: ["id"];
          },
        ];
      };
      envelope_events: {
        Row: {
          created_at: string;
          envelope_id: string;
          id: string;
          ip: string | null;
          metadata: Json;
          signer_id: string | null;
          type: Database["public"]["Enums"]["envelope_event_type"];
          user_agent: string | null;
        };
        Insert: {
          created_at?: string;
          envelope_id: string;
          id?: string;
          ip?: string | null;
          metadata?: Json;
          signer_id?: string | null;
          type: Database["public"]["Enums"]["envelope_event_type"];
          user_agent?: string | null;
        };
        Update: {
          created_at?: string;
          envelope_id?: string;
          id?: string;
          ip?: string | null;
          metadata?: Json;
          signer_id?: string | null;
          type?: Database["public"]["Enums"]["envelope_event_type"];
          user_agent?: string | null;
        };
        Relationships: [
          {
            foreignKeyName: "envelope_events_envelope_id_fkey";
            columns: ["envelope_id"];
            isOneToOne: false;
            referencedRelation: "envelopes";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "envelope_events_signer_id_fkey";
            columns: ["signer_id"];
            isOneToOne: false;
            referencedRelation: "signers";
            referencedColumns: ["id"];
          },
        ];
      };
      envelopes: {
        Row: {
          all_signed_at: string | null;
          canceled_at: string | null;
          completed_at: string | null;
          created_at: string;
          declined_at: string | null;
          expired_at: string | null;
          expires_at: string | null;
          expiry_days: number;
          id: string;
          locale: string;
          message: string | null;
          reminder_days: number;
          sender_company: string | null;
          sender_email: string | null;
          sender_name: string | null;
          sent_at: string | null;
          sequential: boolean;
          status: Database["public"]["Enums"]["envelope_status"];
          title: string;
          updated_at: string;
          user_id: string | null;
          verification_code: string | null;
        };
        Insert: {
          all_signed_at?: string | null;
          canceled_at?: string | null;
          completed_at?: string | null;
          created_at?: string;
          declined_at?: string | null;
          expired_at?: string | null;
          expires_at?: string | null;
          expiry_days?: number;
          id?: string;
          locale?: string;
          message?: string | null;
          reminder_days?: number;
          sender_company?: string | null;
          sender_email?: string | null;
          sender_name?: string | null;
          sent_at?: string | null;
          sequential?: boolean;
          status?: Database["public"]["Enums"]["envelope_status"];
          title?: string;
          updated_at?: string;
          user_id?: string | null;
          verification_code?: string | null;
        };
        Update: {
          all_signed_at?: string | null;
          canceled_at?: string | null;
          completed_at?: string | null;
          created_at?: string;
          declined_at?: string | null;
          expired_at?: string | null;
          expires_at?: string | null;
          expiry_days?: number;
          id?: string;
          locale?: string;
          message?: string | null;
          reminder_days?: number;
          sender_company?: string | null;
          sender_email?: string | null;
          sender_name?: string | null;
          sent_at?: string | null;
          sequential?: boolean;
          status?: Database["public"]["Enums"]["envelope_status"];
          title?: string;
          updated_at?: string;
          user_id?: string | null;
          verification_code?: string | null;
        };
        Relationships: [
          {
            foreignKeyName: "envelopes_user_id_fkey";
            columns: ["user_id"];
            isOneToOne: false;
            referencedRelation: "profiles";
            referencedColumns: ["id"];
          },
        ];
      };
      jobs: {
        Row: {
          attempts: number;
          created_at: string;
          dedupe_key: string | null;
          id: string;
          last_error: string | null;
          locked_at: string | null;
          max_attempts: number;
          payload: Json;
          run_at: string;
          status: Database["public"]["Enums"]["job_status"];
          type: string;
          updated_at: string;
        };
        Insert: {
          attempts?: number;
          created_at?: string;
          dedupe_key?: string | null;
          id?: string;
          last_error?: string | null;
          locked_at?: string | null;
          max_attempts?: number;
          payload?: Json;
          run_at?: string;
          status?: Database["public"]["Enums"]["job_status"];
          type: string;
          updated_at?: string;
        };
        Update: {
          attempts?: number;
          created_at?: string;
          dedupe_key?: string | null;
          id?: string;
          last_error?: string | null;
          locked_at?: string | null;
          max_attempts?: number;
          payload?: Json;
          run_at?: string;
          status?: Database["public"]["Enums"]["job_status"];
          type?: string;
          updated_at?: string;
        };
        Relationships: [
        ];
      };
      profiles: {
        Row: {
          company_name: string | null;
          created_at: string;
          email: string;
          first_name: string | null;
          id: string;
          last_name: string | null;
          locale: string;
          logo_path: string | null;
          notify_marketing: boolean;
          notify_on_complete: boolean;
          notify_on_view: boolean;
          onboarding_completed: boolean;
          stripe_customer_id: string | null;
          tax_id: string | null;
          updated_at: string;
        };
        Insert: {
          company_name?: string | null;
          created_at?: string;
          email: string;
          first_name?: string | null;
          id: string;
          last_name?: string | null;
          locale?: string;
          logo_path?: string | null;
          notify_marketing?: boolean;
          notify_on_complete?: boolean;
          notify_on_view?: boolean;
          onboarding_completed?: boolean;
          stripe_customer_id?: string | null;
          tax_id?: string | null;
          updated_at?: string;
        };
        Update: {
          company_name?: string | null;
          created_at?: string;
          email?: string;
          first_name?: string | null;
          id?: string;
          last_name?: string | null;
          locale?: string;
          logo_path?: string | null;
          notify_marketing?: boolean;
          notify_on_complete?: boolean;
          notify_on_view?: boolean;
          onboarding_completed?: boolean;
          stripe_customer_id?: string | null;
          tax_id?: string | null;
          updated_at?: string;
        };
        Relationships: [
        ];
      };
      rate_limits: {
        Row: {
          hits: number;
          key: string;
          window_start: string;
        };
        Insert: {
          hits?: number;
          key: string;
          window_start: string;
        };
        Update: {
          hits?: number;
          key?: string;
          window_start?: string;
        };
        Relationships: [
        ];
      };
      signature_evidence: {
        Row: {
          biometric_data_path: string | null;
          biometric_key_id: string | null;
          biometric_purged_at: string | null;
          biometric_sha256: string;
          client_time: string | null;
          consent_text_version: string | null;
          created_at: string;
          device_type: string | null;
          duration_ms: number;
          envelope_id: string;
          geo_city: string | null;
          geo_country: string | null;
          geo_region: string | null;
          id: string;
          ip: string | null;
          pointer_type: string | null;
          points_count: number;
          pressure_supported: boolean;
          screen_h: number | null;
          screen_w: number | null;
          server_time: string;
          signature_image_path: string | null;
          signature_image_sha256: string | null;
          signer_id: string;
          stroke_count: number;
          timezone: string | null;
          user_agent: string | null;
        };
        Insert: {
          biometric_data_path?: string | null;
          biometric_key_id?: string | null;
          biometric_purged_at?: string | null;
          biometric_sha256: string;
          client_time?: string | null;
          consent_text_version?: string | null;
          created_at?: string;
          device_type?: string | null;
          duration_ms: number;
          envelope_id: string;
          geo_city?: string | null;
          geo_country?: string | null;
          geo_region?: string | null;
          id?: string;
          ip?: string | null;
          pointer_type?: string | null;
          points_count: number;
          pressure_supported?: boolean;
          screen_h?: number | null;
          screen_w?: number | null;
          server_time?: string;
          signature_image_path?: string | null;
          signature_image_sha256?: string | null;
          signer_id: string;
          stroke_count: number;
          timezone?: string | null;
          user_agent?: string | null;
        };
        Update: {
          biometric_data_path?: string | null;
          biometric_key_id?: string | null;
          biometric_purged_at?: string | null;
          biometric_sha256?: string;
          client_time?: string | null;
          consent_text_version?: string | null;
          created_at?: string;
          device_type?: string | null;
          duration_ms?: number;
          envelope_id?: string;
          geo_city?: string | null;
          geo_country?: string | null;
          geo_region?: string | null;
          id?: string;
          ip?: string | null;
          pointer_type?: string | null;
          points_count?: number;
          pressure_supported?: boolean;
          screen_h?: number | null;
          screen_w?: number | null;
          server_time?: string;
          signature_image_path?: string | null;
          signature_image_sha256?: string | null;
          signer_id?: string;
          stroke_count?: number;
          timezone?: string | null;
          user_agent?: string | null;
        };
        Relationships: [
          {
            foreignKeyName: "signature_evidence_envelope_id_fkey";
            columns: ["envelope_id"];
            isOneToOne: false;
            referencedRelation: "envelopes";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "signature_evidence_signer_id_fkey";
            columns: ["signer_id"];
            isOneToOne: true;
            referencedRelation: "signers";
            referencedColumns: ["id"];
          },
        ];
      };
      signed_documents: {
        Row: {
          created_at: string;
          document_id: string | null;
          envelope_id: string;
          evidence_pdf_path: string | null;
          evidence_sha256: string | null;
          id: string;
          kind: Database["public"]["Enums"]["signed_artifact_kind"];
          signed_path: string;
          signed_sha256: string;
          size_bytes: number | null;
          tsa_attempts: number;
          tsa_error: string | null;
          tsa_gen_time: string | null;
          tsa_hash_alg: string | null;
          tsa_name: string | null;
          tsa_next_attempt_at: string | null;
          tsa_policy_oid: string | null;
          tsa_provider: string | null;
          tsa_serial: string | null;
          tsa_status: Database["public"]["Enums"]["tsa_status"];
          tsq_path: string | null;
          tsr_path: string | null;
          updated_at: string;
        };
        Insert: {
          created_at?: string;
          document_id?: string | null;
          envelope_id: string;
          evidence_pdf_path?: string | null;
          evidence_sha256?: string | null;
          id?: string;
          kind?: Database["public"]["Enums"]["signed_artifact_kind"];
          signed_path: string;
          signed_sha256: string;
          size_bytes?: number | null;
          tsa_attempts?: number;
          tsa_error?: string | null;
          tsa_gen_time?: string | null;
          tsa_hash_alg?: string | null;
          tsa_name?: string | null;
          tsa_next_attempt_at?: string | null;
          tsa_policy_oid?: string | null;
          tsa_provider?: string | null;
          tsa_serial?: string | null;
          tsa_status?: Database["public"]["Enums"]["tsa_status"];
          tsq_path?: string | null;
          tsr_path?: string | null;
          updated_at?: string;
        };
        Update: {
          created_at?: string;
          document_id?: string | null;
          envelope_id?: string;
          evidence_pdf_path?: string | null;
          evidence_sha256?: string | null;
          id?: string;
          kind?: Database["public"]["Enums"]["signed_artifact_kind"];
          signed_path?: string;
          signed_sha256?: string;
          size_bytes?: number | null;
          tsa_attempts?: number;
          tsa_error?: string | null;
          tsa_gen_time?: string | null;
          tsa_hash_alg?: string | null;
          tsa_name?: string | null;
          tsa_next_attempt_at?: string | null;
          tsa_policy_oid?: string | null;
          tsa_provider?: string | null;
          tsa_serial?: string | null;
          tsa_status?: Database["public"]["Enums"]["tsa_status"];
          tsq_path?: string | null;
          tsr_path?: string | null;
          updated_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: "signed_documents_document_id_fkey";
            columns: ["document_id"];
            isOneToOne: false;
            referencedRelation: "documents";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "signed_documents_envelope_id_fkey";
            columns: ["envelope_id"];
            isOneToOne: false;
            referencedRelation: "envelopes";
            referencedColumns: ["id"];
          },
        ];
      };
      signer_access_tokens: {
        Row: {
          created_at: string;
          expires_at: string;
          revoked_at: string | null;
          signer_id: string;
          token_hash: string;
        };
        Insert: {
          created_at?: string;
          expires_at: string;
          revoked_at?: string | null;
          signer_id: string;
          token_hash: string;
        };
        Update: {
          created_at?: string;
          expires_at?: string;
          revoked_at?: string | null;
          signer_id?: string;
          token_hash?: string;
        };
        Relationships: [
          {
            foreignKeyName: "signer_access_tokens_signer_id_fkey";
            columns: ["signer_id"];
            isOneToOne: false;
            referencedRelation: "signers";
            referencedColumns: ["id"];
          },
        ];
      };
      signers: {
        Row: {
          consent_accepted_at: string | null;
          consent_text_version: string | null;
          created_at: string;
          decline_reason: string | null;
          declined_at: string | null;
          email: string;
          envelope_id: string;
          first_name: string;
          id: string;
          last_name: string;
          last_reminder_at: string | null;
          order_index: number;
          reminder_count: number;
          sent_at: string | null;
          signed_at: string | null;
          status: Database["public"]["Enums"]["signer_status"];
          token_expires_at: string | null;
          token_hash: string | null;
          updated_at: string;
          viewed_at: string | null;
        };
        Insert: {
          consent_accepted_at?: string | null;
          consent_text_version?: string | null;
          created_at?: string;
          decline_reason?: string | null;
          declined_at?: string | null;
          email: string;
          envelope_id: string;
          first_name: string;
          id?: string;
          last_name: string;
          last_reminder_at?: string | null;
          order_index?: number;
          reminder_count?: number;
          sent_at?: string | null;
          signed_at?: string | null;
          status?: Database["public"]["Enums"]["signer_status"];
          token_expires_at?: string | null;
          token_hash?: string | null;
          updated_at?: string;
          viewed_at?: string | null;
        };
        Update: {
          consent_accepted_at?: string | null;
          consent_text_version?: string | null;
          created_at?: string;
          decline_reason?: string | null;
          declined_at?: string | null;
          email?: string;
          envelope_id?: string;
          first_name?: string;
          id?: string;
          last_name?: string;
          last_reminder_at?: string | null;
          order_index?: number;
          reminder_count?: number;
          sent_at?: string | null;
          signed_at?: string | null;
          status?: Database["public"]["Enums"]["signer_status"];
          token_expires_at?: string | null;
          token_hash?: string | null;
          updated_at?: string;
          viewed_at?: string | null;
        };
        Relationships: [
          {
            foreignKeyName: "signers_envelope_id_fkey";
            columns: ["envelope_id"];
            isOneToOne: false;
            referencedRelation: "envelopes";
            referencedColumns: ["id"];
          },
        ];
      };
      stripe_events: {
        Row: {
          created_at: string;
          error: string | null;
          id: string;
          payload: Json;
          processed_at: string | null;
          type: string;
        };
        Insert: {
          created_at?: string;
          error?: string | null;
          id: string;
          payload: Json;
          processed_at?: string | null;
          type: string;
        };
        Update: {
          created_at?: string;
          error?: string | null;
          id?: string;
          payload?: Json;
          processed_at?: string | null;
          type?: string;
        };
        Relationships: [
        ];
      };
      subscriptions: {
        Row: {
          cancel_at_period_end: boolean;
          canceled_at: string | null;
          created_at: string;
          current_period_end: string | null;
          current_period_start: string | null;
          id: string;
          price_id: string | null;
          status: Database["public"]["Enums"]["subscription_status"];
          stripe_subscription_id: string;
          updated_at: string;
          user_id: string;
        };
        Insert: {
          cancel_at_period_end?: boolean;
          canceled_at?: string | null;
          created_at?: string;
          current_period_end?: string | null;
          current_period_start?: string | null;
          id?: string;
          price_id?: string | null;
          status: Database["public"]["Enums"]["subscription_status"];
          stripe_subscription_id: string;
          updated_at?: string;
          user_id: string;
        };
        Update: {
          cancel_at_period_end?: boolean;
          canceled_at?: string | null;
          created_at?: string;
          current_period_end?: string | null;
          current_period_start?: string | null;
          id?: string;
          price_id?: string | null;
          status?: Database["public"]["Enums"]["subscription_status"];
          stripe_subscription_id?: string;
          updated_at?: string;
          user_id?: string;
        };
        Relationships: [
          {
            foreignKeyName: "subscriptions_user_id_fkey";
            columns: ["user_id"];
            isOneToOne: false;
            referencedRelation: "profiles";
            referencedColumns: ["id"];
          },
        ];
      };
    };
    Views: { [_ in never]: never };
    Functions: {
      adjust_credits: { Args: { p_user_id: string; p_amount: number; p_note: string }; Returns: undefined };
      cancel_envelope: { Args: { p_envelope_id: string; p_user_id: string }; Returns: Json };
      claim_expired_biometrics: { Args: { p_years: number; p_limit?: number }; Returns: { evidence_id: string; biometric_data_path: string }[] };
      claim_job_by_key: { Args: { p_dedupe_key: string }; Returns: { id: string; type: string; payload: Json; status: Database["public"]["Enums"]["job_status"]; run_at: string; attempts: number; max_attempts: number; last_error: string; locked_at: string; dedupe_key: string; created_at: string; updated_at: string }[] };
      claim_jobs: { Args: { p_type: string; p_limit?: number }; Returns: { id: string; type: string; payload: Json; status: Database["public"]["Enums"]["job_status"]; run_at: string; attempts: number; max_attempts: number; last_error: string; locked_at: string; dedupe_key: string; created_at: string; updated_at: string }[] };
      complete_job: { Args: { p_job_id: string }; Returns: undefined };
      complete_signature: { Args: { p_token_hash: string; p_evidence: Json; p_consent_version: string; p_ip?: string; p_user_agent?: string }; Returns: Json };
      consume_credit: { Args: { p_signer_id: string }; Returns: boolean };
      decline_signature: { Args: { p_token_hash: string; p_reason?: string; p_ip?: string; p_user_agent?: string }; Returns: Json };
      delete_draft_envelope: { Args: { p_envelope_id: string; p_user_id: string }; Returns: undefined };
      delete_user_account: { Args: { p_user_id: string }; Returns: Json };
      enqueue_job: { Args: { p_type: string; p_payload: Json; p_run_at?: string; p_dedupe_key?: string; p_max_attempts?: number }; Returns: string };
      expire_due_envelopes: { Args: { p_limit?: number }; Returns: { envelope_id: string; released: number }[] };
      fail_job: { Args: { p_job_id: string; p_error: string; p_retry_at?: string }; Returns: Database["public"]["Enums"]["job_status"] };
      get_available_credits: { Args: { p_user_id: string }; Returns: { monthly_available: number; pack_available: number; total: number; monthly_granted: number; monthly_expires_at: string; reserved: number }[] };
      grant_monthly_credits: { Args: { p_user_id: string; p_amount: number; p_expires_at: string; p_invoice_id: string }; Returns: boolean };
      grant_pack_credits: { Args: { p_user_id: string; p_amount: number; p_payment_ref: string; p_pack_id?: string }; Returns: boolean };
      issue_signer_token: { Args: { p_signer_id: string; p_token_hash: string }; Returns: undefined };
      log_envelope_event: { Args: { p_envelope_id: string; p_signer_id: string; p_type: Database["public"]["Enums"]["envelope_event_type"]; p_metadata?: Json; p_ip?: string; p_user_agent?: string }; Returns: string };
      mark_envelope_completed: { Args: { p_envelope_id: string }; Returns: boolean };
      mark_signer_viewed: { Args: { p_token_hash: string; p_ip?: string; p_user_agent?: string }; Returns: Json };
      owns_draft_envelope: { Args: { p_envelope_id: string }; Returns: boolean };
      owns_envelope: { Args: { p_envelope_id: string }; Returns: boolean };
      provision_user: { Args: { p_user_id: string }; Returns: { id: string; email: string; first_name: string; last_name: string; company_name: string; tax_id: string; locale: string; logo_path: string; stripe_customer_id: string; onboarding_completed: boolean; notify_on_view: boolean; notify_on_complete: boolean; notify_marketing: boolean; created_at: string; updated_at: string } };
      rate_limit_hit: { Args: { p_key: string; p_limit: number; p_window_seconds: number }; Returns: { allowed: boolean; remaining: number; reset_at: string }[] };
      record_reminder: { Args: { p_signer_id: string; p_resend_id?: string }; Returns: undefined };
      record_signer_event: { Args: { p_token_hash: string; p_type: Database["public"]["Enums"]["envelope_event_type"]; p_metadata?: Json; p_ip?: string; p_user_agent?: string }; Returns: undefined };
      record_tsa_result: { Args: { p_artifact_id: string; p_granted: boolean; p_fields: Json; p_error?: string; p_next_attempt_at?: string }; Returns: { id: string; envelope_id: string; kind: Database["public"]["Enums"]["signed_artifact_kind"]; document_id: string; signed_path: string; signed_sha256: string; size_bytes: number; evidence_pdf_path: string; evidence_sha256: string; tsa_provider: string; tsq_path: string; tsr_path: string; tsa_serial: string; tsa_gen_time: string; tsa_policy_oid: string; tsa_name: string; tsa_hash_alg: string; tsa_status: Database["public"]["Enums"]["tsa_status"]; tsa_error: string; tsa_attempts: number; tsa_next_attempt_at: string; created_at: string; updated_at: string } };
      release_credit: { Args: { p_signer_id: string; p_note?: string }; Returns: boolean };
      reserve_credits: { Args: { p_user_id: string; p_envelope_id: string; p_signer_ids: string[] }; Returns: undefined };
      send_envelope: { Args: { p_envelope_id: string; p_user_id: string; p_tokens: Json; p_verification_code: string; p_expires_at: string; p_sender?: Json }; Returns: Json };
    };
    Enums: {
      credit_kind: "monthly_grant" | "pack_purchase" | "trial_grant" | "reserve" | "consume" | "release" | "adjustment";
      credit_pool: "monthly" | "pack";
      envelope_event_type: "created" | "sent" | "email_sent" | "email_delivered" | "email_failed" | "opened" | "document_viewed" | "scrolled_to_end" | "consent_accepted" | "signed" | "declined" | "reminder_sent" | "completed" | "expired" | "canceled" | "tsa_granted" | "tsa_failed" | "downloaded";
      envelope_status: "draft" | "sent" | "viewed" | "completed" | "declined" | "expired" | "canceled";
      job_status: "pending" | "running" | "done" | "failed";
      signed_artifact_kind: "document" | "evidence";
      signer_status: "pending" | "sent" | "viewed" | "signed" | "declined";
      subscription_status: "trialing" | "active" | "past_due" | "canceled" | "unpaid" | "incomplete" | "incomplete_expired" | "paused";
      tsa_status: "pending" | "granted" | "failed";
    };
    CompositeTypes: { [_ in never]: never };
  };
};

type PublicSchema = Database["public"];
export type Tables<T extends keyof PublicSchema["Tables"]> = PublicSchema["Tables"][T]["Row"];
export type TablesInsert<T extends keyof PublicSchema["Tables"]> = PublicSchema["Tables"][T]["Insert"];
export type TablesUpdate<T extends keyof PublicSchema["Tables"]> = PublicSchema["Tables"][T]["Update"];
export type Enums<T extends keyof PublicSchema["Enums"]> = PublicSchema["Enums"][T];

export const Constants = {
  public: {
    Enums: {
      credit_kind: ["monthly_grant", "pack_purchase", "trial_grant", "reserve", "consume", "release", "adjustment"],
      credit_pool: ["monthly", "pack"],
      envelope_event_type: ["created", "sent", "email_sent", "email_delivered", "email_failed", "opened", "document_viewed", "scrolled_to_end", "consent_accepted", "signed", "declined", "reminder_sent", "completed", "expired", "canceled", "tsa_granted", "tsa_failed", "downloaded"],
      envelope_status: ["draft", "sent", "viewed", "completed", "declined", "expired", "canceled"],
      job_status: ["pending", "running", "done", "failed"],
      signed_artifact_kind: ["document", "evidence"],
      signer_status: ["pending", "sent", "viewed", "signed", "declined"],
      subscription_status: ["trialing", "active", "past_due", "canceled", "unpaid", "incomplete", "incomplete_expired", "paused"],
      tsa_status: ["pending", "granted", "failed"],
    },
  },
} as const;
