-- DocuFirma: every migration in supabase/migrations, for the Supabase SQL Editor.
-- GENERATED by `pnpm db:bundle` — do not edit by hand.
-- Runs in one transaction: if anything fails, nothing is applied. Paste it as a whole.
begin;

-- ===== 20260923100000_init_schema.sql =====
-- ─────────────────────────────────────────────────────────────────────────────
-- DocuFirma · core schema
-- Enums, tables, updated_at triggers and indexes. RLS lives in *_rls.sql,
-- credit ledger logic in *_credits.sql, envelope workflow in *_envelopes.sql.
-- ─────────────────────────────────────────────────────────────────────────────

create extension if not exists pgcrypto with schema extensions;

-- ── Enums ────────────────────────────────────────────────────────────────────
create type public.envelope_status as enum (
  'draft', 'sent', 'viewed', 'completed', 'declined', 'expired', 'canceled'
);

create type public.signer_status as enum ('pending', 'sent', 'viewed', 'signed', 'declined');

create type public.subscription_status as enum (
  'trialing', 'active', 'past_due', 'canceled', 'unpaid', 'incomplete', 'incomplete_expired', 'paused'
);

create type public.credit_kind as enum (
  'monthly_grant', 'pack_purchase', 'trial_grant', 'reserve', 'consume', 'release', 'adjustment'
);

create type public.credit_pool as enum ('monthly', 'pack');

create type public.tsa_status as enum ('pending', 'granted', 'failed');

create type public.signed_artifact_kind as enum ('document', 'evidence');

create type public.envelope_event_type as enum (
  'created', 'sent', 'email_sent', 'email_delivered', 'email_failed', 'opened', 'document_viewed',
  'scrolled_to_end', 'consent_accepted', 'signed', 'declined', 'reminder_sent', 'completed',
  'expired', 'canceled', 'tsa_granted', 'tsa_failed', 'downloaded'
);

create type public.job_status as enum ('pending', 'running', 'done', 'failed');

-- ── Helpers ──────────────────────────────────────────────────────────────────
create or replace function public.set_updated_at()
returns trigger
language plpgsql
set search_path = ''
as $$
begin
  new.updated_at := now();
  return new;
end;
$$;

-- ── App settings (small key/value store editable by operators) ───────────────
create table public.app_settings (
  key text primary key,
  value jsonb not null,
  updated_at timestamptz not null default now()
);

insert into public.app_settings (key, value) values
  ('trial_credits', '3'::jsonb),
  ('monthly_credits', '10'::jsonb)
on conflict (key) do nothing;

-- ── Profiles (1:1 with auth.users) ───────────────────────────────────────────
create table public.profiles (
  id uuid primary key references auth.users (id) on delete cascade,
  email text not null,
  first_name text,
  last_name text,
  company_name text,
  tax_id text,
  locale text not null default 'es' check (locale in ('es', 'en')),
  logo_path text,
  stripe_customer_id text unique,
  onboarding_completed boolean not null default false,
  notify_on_view boolean not null default true,
  notify_on_complete boolean not null default true,
  notify_marketing boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint profiles_first_name_len check (char_length(first_name) <= 80),
  constraint profiles_last_name_len check (char_length(last_name) <= 120),
  constraint profiles_company_len check (char_length(company_name) <= 160),
  constraint profiles_tax_id_len check (char_length(tax_id) <= 32)
);

create trigger profiles_updated_at before update on public.profiles
  for each row execute function public.set_updated_at();

-- ── Subscriptions (mirror of Stripe) ─────────────────────────────────────────
create table public.subscriptions (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references public.profiles (id) on delete cascade,
  stripe_subscription_id text not null unique,
  status public.subscription_status not null,
  price_id text,
  current_period_start timestamptz,
  current_period_end timestamptz,
  cancel_at_period_end boolean not null default false,
  canceled_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index subscriptions_user_idx on public.subscriptions (user_id, status);
create trigger subscriptions_updated_at before update on public.subscriptions
  for each row execute function public.set_updated_at();

-- ── Credit packs catalog ─────────────────────────────────────────────────────
create table public.credit_packs (
  id uuid primary key default gen_random_uuid(),
  slug text not null unique,
  name_es text not null,
  name_en text not null,
  credits integer not null check (credits > 0),
  price_cents integer not null check (price_cents >= 0),
  currency text not null default 'eur',
  stripe_price_id text unique,
  active boolean not null default true,
  sort_order integer not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create trigger credit_packs_updated_at before update on public.credit_packs
  for each row execute function public.set_updated_at();

-- ── Envelopes ────────────────────────────────────────────────────────────────
create table public.envelopes (
  id uuid primary key default gen_random_uuid(),
  -- Nullable: completed envelopes outlive a deleted account for the legal retention period.
  user_id uuid references public.profiles (id) on delete set null,
  title text not null default '',
  message text,
  status public.envelope_status not null default 'draft',
  locale text not null default 'es' check (locale in ('es', 'en')),
  sequential boolean not null default false,
  reminder_days integer not null default 3 check (reminder_days between 0 and 30),
  expires_at timestamptz,
  sent_at timestamptz,
  completed_at timestamptz,
  declined_at timestamptz,
  canceled_at timestamptz,
  expired_at timestamptz,
  verification_code text unique,
  -- Snapshot of the sender identity at send time (emails, evidence, verification).
  sender_name text,
  sender_email text,
  sender_company text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint envelopes_title_len check (char_length(title) <= 200),
  constraint envelopes_message_len check (char_length(message) <= 2000),
  constraint envelopes_verification_code_format
    check (verification_code is null or verification_code ~ '^DF-[0-9A-Z]{4}-[0-9A-Z]{4}$')
);

create index envelopes_user_status_idx on public.envelopes (user_id, status, created_at desc);
create index envelopes_expiry_idx on public.envelopes (expires_at) where status in ('sent', 'viewed');
create trigger envelopes_updated_at before update on public.envelopes
  for each row execute function public.set_updated_at();

-- ── Documents (original files of an envelope) ───────────────────────────────
create table public.documents (
  id uuid primary key default gen_random_uuid(),
  envelope_id uuid not null references public.envelopes (id) on delete cascade,
  name text not null,
  original_path text not null,
  original_sha256 text not null check (original_sha256 ~ '^[0-9a-f]{64}$'),
  source_mime_type text,
  mime_type text not null default 'application/pdf',
  page_count integer not null check (page_count > 0),
  size_bytes bigint not null check (size_bytes > 0),
  order_index integer not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint documents_name_len check (char_length(name) <= 255)
);

create index documents_envelope_idx on public.documents (envelope_id, order_index);
create trigger documents_updated_at before update on public.documents
  for each row execute function public.set_updated_at();

-- ── Signers ──────────────────────────────────────────────────────────────────
create table public.signers (
  id uuid primary key default gen_random_uuid(),
  envelope_id uuid not null references public.envelopes (id) on delete cascade,
  first_name text not null,
  last_name text not null,
  email text not null,
  order_index integer not null default 0,
  status public.signer_status not null default 'pending',
  token_hash text unique check (token_hash is null or token_hash ~ '^[0-9a-f]{64}$'),
  token_expires_at timestamptz,
  sent_at timestamptz,
  viewed_at timestamptz,
  signed_at timestamptz,
  declined_at timestamptz,
  decline_reason text,
  consent_accepted_at timestamptz,
  consent_text_version text,
  reminder_count integer not null default 0,
  last_reminder_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint signers_first_name_len check (char_length(first_name) between 1 and 80),
  constraint signers_last_name_len check (char_length(last_name) between 1 and 120),
  constraint signers_email_format check (email ~* '^[^@\s]+@[^@\s]+\.[^@\s]+$' and char_length(email) <= 254),
  constraint signers_decline_reason_len check (char_length(decline_reason) <= 1000)
);

create unique index signers_envelope_email_uidx on public.signers (envelope_id, lower(email));
create index signers_envelope_idx on public.signers (envelope_id, order_index);
create index signers_reminder_idx on public.signers (status, last_reminder_at) where status in ('sent', 'viewed');
create trigger signers_updated_at before update on public.signers
  for each row execute function public.set_updated_at();

-- ── Signature evidence (biometrics + context). Service role only. ───────────
create table public.signature_evidence (
  id uuid primary key default gen_random_uuid(),
  signer_id uuid not null unique references public.signers (id) on delete cascade,
  envelope_id uuid not null references public.envelopes (id) on delete cascade,
  biometric_data_path text,
  biometric_sha256 text not null check (biometric_sha256 ~ '^[0-9a-f]{64}$'),
  biometric_key_id text,
  signature_image_path text,
  signature_image_sha256 text,
  stroke_count integer not null,
  duration_ms integer not null,
  points_count integer not null,
  device_type text,
  user_agent text,
  ip inet,
  geo_country text,
  geo_region text,
  geo_city text,
  screen_w integer,
  screen_h integer,
  pointer_type text check (pointer_type in ('pen', 'touch', 'mouse')),
  pressure_supported boolean not null default false,
  timezone text,
  client_time timestamptz,
  server_time timestamptz not null default now(),
  consent_text_version text,
  created_at timestamptz not null default now()
);

create index signature_evidence_envelope_idx on public.signature_evidence (envelope_id);

-- ── Signed artifacts (signed PDFs + evidence certificate) and their timestamps
create table public.signed_documents (
  id uuid primary key default gen_random_uuid(),
  envelope_id uuid not null references public.envelopes (id) on delete cascade,
  kind public.signed_artifact_kind not null default 'document',
  document_id uuid references public.documents (id) on delete cascade,
  signed_path text not null,
  signed_sha256 text not null check (signed_sha256 ~ '^[0-9a-f]{64}$'),
  size_bytes bigint,
  -- Evidence certificate of the envelope (same for every document row, kept for convenience)
  evidence_pdf_path text,
  evidence_sha256 text,
  tsa_provider text check (tsa_provider in ('MENSATEK', 'FNMT', 'TEST')),
  tsq_path text,
  tsr_path text,
  tsa_serial text,
  tsa_gen_time timestamptz,
  tsa_policy_oid text,
  tsa_name text,
  tsa_hash_alg text,
  tsa_status public.tsa_status not null default 'pending',
  tsa_error text,
  tsa_attempts integer not null default 0,
  tsa_next_attempt_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint signed_documents_kind_doc check (
    (kind = 'document' and document_id is not null) or (kind = 'evidence' and document_id is null)
  )
);

create unique index signed_documents_document_uidx on public.signed_documents (document_id) where kind = 'document';
create unique index signed_documents_evidence_uidx on public.signed_documents (envelope_id) where kind = 'evidence';
create index signed_documents_sha_idx on public.signed_documents (signed_sha256);
create index signed_documents_tsa_retry_idx on public.signed_documents (tsa_status, tsa_next_attempt_at)
  where tsa_status <> 'granted';
create trigger signed_documents_updated_at before update on public.signed_documents
  for each row execute function public.set_updated_at();

-- ── Envelope events: immutable audit trail (append-only) ────────────────────
create table public.envelope_events (
  id uuid primary key default gen_random_uuid(),
  envelope_id uuid not null references public.envelopes (id) on delete cascade,
  signer_id uuid references public.signers (id) on delete set null,
  type public.envelope_event_type not null,
  metadata jsonb not null default '{}'::jsonb,
  ip inet,
  user_agent text,
  created_at timestamptz not null default now()
);

create index envelope_events_envelope_idx on public.envelope_events (envelope_id, created_at);
create index envelope_events_signer_idx on public.envelope_events (signer_id, type);

-- Updates/deletes are rejected unless a privileged function explicitly opts in for
-- the current transaction (GDPR anonymisation, account deletion, retention purge).
create or replace function public.envelope_events_guard()
returns trigger
language plpgsql
set search_path = ''
as $$
begin
  if tg_op = 'DELETE' then
    if coalesce(current_setting('docufirma.allow_purge', true), '') = 'on' then
      return old;
    end if;
    raise exception 'envelope_events is append-only (delete rejected)' using errcode = '42501';
  end if;

  -- UPDATE: only anonymisation of ip / user_agent is ever allowed.
  if coalesce(current_setting('docufirma.allow_event_anonymization', true), '') = 'on'
     and new.id = old.id and new.envelope_id = old.envelope_id and new.type = old.type
     and new.created_at = old.created_at and new.ip is null and new.user_agent is null
  then
    return new;
  end if;
  -- ON DELETE SET NULL of signer_id during a purge is allowed as well.
  if coalesce(current_setting('docufirma.allow_purge', true), '') = 'on' then
    return new;
  end if;
  raise exception 'envelope_events is append-only (update rejected)' using errcode = '42501';
end;
$$;

create trigger envelope_events_append_only
  before update or delete on public.envelope_events
  for each row execute function public.envelope_events_guard();

-- ── Contacts (sender address book) ───────────────────────────────────────────
create table public.contacts (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references public.profiles (id) on delete cascade,
  first_name text not null,
  last_name text not null,
  email text not null,
  last_used_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint contacts_first_name_len check (char_length(first_name) between 1 and 80),
  constraint contacts_last_name_len check (char_length(last_name) between 1 and 120),
  constraint contacts_email_format check (email ~* '^[^@\s]+@[^@\s]+\.[^@\s]+$' and char_length(email) <= 254)
);

create unique index contacts_user_email_uidx on public.contacts (user_id, lower(email));
create trigger contacts_updated_at before update on public.contacts
  for each row execute function public.set_updated_at();

-- ── Stripe webhook idempotency ───────────────────────────────────────────────
create table public.stripe_events (
  id text primary key,
  type text not null,
  payload jsonb not null,
  processed_at timestamptz,
  error text,
  created_at timestamptz not null default now()
);

-- ── Background jobs (simple Postgres queue) ─────────────────────────────────
create table public.jobs (
  id uuid primary key default gen_random_uuid(),
  type text not null,
  payload jsonb not null default '{}'::jsonb,
  status public.job_status not null default 'pending',
  run_at timestamptz not null default now(),
  attempts integer not null default 0,
  max_attempts integer not null default 6,
  last_error text,
  locked_at timestamptz,
  dedupe_key text unique,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index jobs_due_idx on public.jobs (type, status, run_at) where status in ('pending', 'running');
create trigger jobs_updated_at before update on public.jobs
  for each row execute function public.set_updated_at();

-- ── Rate limiting fallback (when Upstash is not configured) ────────────────
create table public.rate_limits (
  key text not null,
  window_start timestamptz not null,
  hits integer not null default 0,
  primary key (key, window_start)
);

create index rate_limits_window_idx on public.rate_limits (window_start);

-- ── Deleted accounts (accounting reconciliation only; no personal data) ─────
create table public.deleted_accounts (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null,
  email_sha256 text not null,
  stripe_customer_id text,
  deleted_at timestamptz not null default now()
);

-- ===== 20260923100100_credits.sql =====
-- ─────────────────────────────────────────────────────────────────────────────
-- DocuFirma · credit ledger ("firmas")
--
-- The balance is never stored: it is always the sum of the ledger.
--  * monthly_grant  +N  pool=monthly  expires_at = end of the billing period
--  * pack_purchase  +N  pool=pack     no expiry
--  * trial_grant    +N  pool=pack     no expiry (trial credits behave like a pack)
--  * reserve        -1  per signer when an envelope is sent (monthly first, then pack)
--  * consume         0  marker: the reservation became a completed signature
--  * release        +1  the reservation is returned (declined / canceled / expired)
--  * adjustment     ±N  manual correction by an operator
--
-- Monthly rows (grant, reserve, release) carry the expires_at of the cycle they belong
-- to, so a whole cycle disappears from the balance when it ends: monthly credits never
-- accumulate. Only the latest non-expired cycle counts.
-- ─────────────────────────────────────────────────────────────────────────────

create table public.credit_ledger (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references public.profiles (id) on delete cascade,
  kind public.credit_kind not null,
  amount integer not null,
  pool public.credit_pool not null,
  expires_at timestamptz,
  envelope_id uuid references public.envelopes (id) on delete set null,
  signer_id uuid references public.signers (id) on delete set null,
  pack_id uuid references public.credit_packs (id) on delete set null,
  stripe_payment_intent_id text,
  stripe_invoice_id text,
  note text,
  created_at timestamptz not null default now(),
  constraint credit_ledger_amount_sign check (
    (kind = 'consume' and amount = 0)
    or (kind in ('monthly_grant', 'pack_purchase', 'trial_grant', 'release') and amount > 0)
    or (kind = 'reserve' and amount < 0)
    or (kind = 'adjustment' and amount <> 0)
  ),
  constraint credit_ledger_monthly_expiry check (pool <> 'monthly' or expires_at is not null)
);

create index credit_ledger_user_idx on public.credit_ledger (user_id, pool, expires_at);
create index credit_ledger_signer_idx on public.credit_ledger (signer_id);
-- Idempotency: one reserve / consume / release per signer, one grant per invoice / payment.
create unique index credit_ledger_reserve_uidx on public.credit_ledger (signer_id) where kind = 'reserve';
create unique index credit_ledger_consume_uidx on public.credit_ledger (signer_id) where kind = 'consume';
create unique index credit_ledger_release_uidx on public.credit_ledger (signer_id) where kind = 'release';
create unique index credit_ledger_invoice_uidx on public.credit_ledger (stripe_invoice_id) where kind = 'monthly_grant';
create unique index credit_ledger_payment_uidx on public.credit_ledger (stripe_payment_intent_id) where kind = 'pack_purchase';
create unique index credit_ledger_trial_uidx on public.credit_ledger (user_id) where kind = 'trial_grant';

-- The ledger is append-only (purges only through privileged functions).
create or replace function public.credit_ledger_guard()
returns trigger
language plpgsql
set search_path = ''
as $$
begin
  if coalesce(current_setting('docufirma.allow_purge', true), '') = 'on' then
    return case when tg_op = 'DELETE' then old else new end;
  end if;
  raise exception 'credit_ledger is append-only' using errcode = '42501';
end;
$$;

create trigger credit_ledger_append_only
  before update or delete on public.credit_ledger
  for each row execute function public.credit_ledger_guard();

-- ── Balance ──────────────────────────────────────────────────────────────────
-- Internal: balance for a user without permission checks.
create or replace function public._credit_balance(p_user_id uuid)
returns table (
  monthly_available integer,
  pack_available integer,
  monthly_granted integer,
  monthly_expires_at timestamptz,
  reserved integer
)
language sql
stable
security definer
set search_path = ''
as $$
  with cycle as (
    select max(l.expires_at) as expires_at
    from public.credit_ledger l
    where l.user_id = p_user_id and l.kind = 'monthly_grant' and l.expires_at > now()
  )
  select
    coalesce((
      select sum(l.amount) from public.credit_ledger l, cycle c
      where l.user_id = p_user_id and l.pool = 'monthly' and l.expires_at = c.expires_at
    ), 0)::integer,
    coalesce((
      select sum(l.amount) from public.credit_ledger l
      where l.user_id = p_user_id and l.pool = 'pack'
    ), 0)::integer,
    coalesce((
      select sum(l.amount) from public.credit_ledger l, cycle c
      where l.user_id = p_user_id and l.kind = 'monthly_grant' and l.expires_at = c.expires_at
    ), 0)::integer,
    (select c.expires_at from cycle c),
    (
      select count(*) from public.credit_ledger r
      where r.user_id = p_user_id and r.kind = 'reserve'
        and not exists (
          select 1 from public.credit_ledger x
          where x.signer_id = r.signer_id and x.kind in ('consume', 'release')
        )
    )::integer
$$;

-- Public: callable by the owner (RLS-like check) or by the service role.
create or replace function public.get_available_credits(p_user_id uuid)
returns table (
  monthly_available integer,
  pack_available integer,
  total integer,
  monthly_granted integer,
  monthly_expires_at timestamptz,
  reserved integer
)
language plpgsql
stable
security definer
set search_path = ''
as $$
begin
  -- Owners may read their own balance; the service role may read any.
  if coalesce(auth.role(), '') <> 'service_role' and auth.uid() is distinct from p_user_id then
    raise exception 'forbidden' using errcode = '42501';
  end if;

  return query
    select greatest(b.monthly_available, 0), greatest(b.pack_available, 0),
           greatest(b.monthly_available, 0) + greatest(b.pack_available, 0),
           b.monthly_granted, b.monthly_expires_at, b.reserved
    from public._credit_balance(p_user_id) b;
end;
$$;

-- Safety net: no insert may leave a pool negative.
create or replace function public.credit_ledger_non_negative()
returns trigger
language plpgsql
set search_path = ''
as $$
declare
  v_balance integer;
begin
  if new.amount >= 0 then
    return new;
  end if;
  if new.pool = 'monthly' then
    select coalesce(sum(amount), 0) into v_balance from public.credit_ledger
    where user_id = new.user_id and pool = 'monthly' and expires_at = new.expires_at;
  else
    select coalesce(sum(amount), 0) into v_balance from public.credit_ledger
    where user_id = new.user_id and pool = 'pack';
  end if;
  if v_balance + new.amount < 0 then
    raise exception 'insufficient_credits' using errcode = 'P0001',
      detail = format('pool=%s balance=%s amount=%s', new.pool, v_balance, new.amount);
  end if;
  return new;
end;
$$;

create trigger credit_ledger_non_negative
  before insert on public.credit_ledger
  for each row execute function public.credit_ledger_non_negative();

-- ── Mutations (service role only) ────────────────────────────────────────────
-- Reserve one credit per signer. Monthly credits are used first, then packs.
-- Serialised per user by locking the profile row.
create or replace function public.reserve_credits(p_user_id uuid, p_envelope_id uuid, p_signer_ids uuid[])
returns void
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_monthly integer;
  v_pack integer;
  v_expires timestamptz;
  v_needed integer;
  v_signer uuid;
begin
  perform 1 from public.profiles where id = p_user_id for update;
  if not found then
    raise exception 'profile_not_found' using errcode = 'P0002';
  end if;

  -- Signers that already hold a reservation are skipped (idempotent retries).
  select count(*) into v_needed from unnest(p_signer_ids) as sid
  where not exists (select 1 from public.credit_ledger l where l.signer_id = sid and l.kind = 'reserve');

  select greatest(b.monthly_available, 0), greatest(b.pack_available, 0), b.monthly_expires_at
    into v_monthly, v_pack, v_expires
  from public._credit_balance(p_user_id) b;

  if v_monthly + v_pack < v_needed then
    raise exception 'insufficient_credits' using errcode = 'P0001',
      detail = format('needed=%s available=%s', v_needed, v_monthly + v_pack);
  end if;

  foreach v_signer in array p_signer_ids loop
    if exists (select 1 from public.credit_ledger where signer_id = v_signer and kind = 'reserve') then
      continue; -- idempotent
    end if;
    if v_monthly > 0 then
      insert into public.credit_ledger (user_id, kind, amount, pool, expires_at, envelope_id, signer_id)
      values (p_user_id, 'reserve', -1, 'monthly', v_expires, p_envelope_id, v_signer);
      v_monthly := v_monthly - 1;
    else
      insert into public.credit_ledger (user_id, kind, amount, pool, envelope_id, signer_id)
      values (p_user_id, 'reserve', -1, 'pack', p_envelope_id, v_signer);
      v_pack := v_pack - 1;
    end if;
  end loop;
end;
$$;

-- Turn a reservation into a consumed signature. Returns false if there was nothing to consume.
create or replace function public.consume_credit(p_signer_id uuid)
returns boolean
language plpgsql
security definer
set search_path = ''
as $$
declare
  r public.credit_ledger;
begin
  select * into r from public.credit_ledger where signer_id = p_signer_id and kind = 'reserve';
  if not found then
    return false;
  end if;
  if exists (select 1 from public.credit_ledger where signer_id = p_signer_id and kind in ('consume', 'release')) then
    return false;
  end if;
  insert into public.credit_ledger (user_id, kind, amount, pool, expires_at, envelope_id, signer_id)
  values (r.user_id, 'consume', 0, r.pool, r.expires_at, r.envelope_id, r.signer_id);
  return true;
end;
$$;

-- Return a reservation to its pool (same cycle for monthly credits).
create or replace function public.release_credit(p_signer_id uuid, p_note text default null)
returns boolean
language plpgsql
security definer
set search_path = ''
as $$
declare
  r public.credit_ledger;
begin
  select * into r from public.credit_ledger where signer_id = p_signer_id and kind = 'reserve';
  if not found then
    return false;
  end if;
  if exists (select 1 from public.credit_ledger where signer_id = p_signer_id and kind in ('consume', 'release')) then
    return false;
  end if;
  insert into public.credit_ledger (user_id, kind, amount, pool, expires_at, envelope_id, signer_id, note)
  values (r.user_id, 'release', -r.amount, r.pool, r.expires_at, r.envelope_id, r.signer_id, p_note);
  return true;
end;
$$;

create or replace function public.grant_monthly_credits(
  p_user_id uuid, p_amount integer, p_expires_at timestamptz, p_invoice_id text
)
returns boolean
language plpgsql
security definer
set search_path = ''
as $$
begin
  insert into public.credit_ledger (user_id, kind, amount, pool, expires_at, stripe_invoice_id)
  values (p_user_id, 'monthly_grant', p_amount, 'monthly', p_expires_at, p_invoice_id)
  on conflict do nothing;
  return found;
end;
$$;

create or replace function public.grant_pack_credits(
  p_user_id uuid, p_amount integer, p_payment_ref text, p_pack_id uuid default null
)
returns boolean
language plpgsql
security definer
set search_path = ''
as $$
begin
  insert into public.credit_ledger (user_id, kind, amount, pool, stripe_payment_intent_id, pack_id)
  values (p_user_id, 'pack_purchase', p_amount, 'pack', p_payment_ref, p_pack_id)
  on conflict do nothing;
  return found;
end;
$$;

create or replace function public.adjust_credits(p_user_id uuid, p_amount integer, p_note text)
returns void
language plpgsql
security definer
set search_path = ''
as $$
begin
  insert into public.credit_ledger (user_id, kind, amount, pool, note)
  values (p_user_id, 'adjustment', p_amount, 'pack', p_note);
end;
$$;

-- ── New users: profile + trial credits ───────────────────────────────────────
create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
declare
  meta jsonb := coalesce(new.raw_user_meta_data, '{}'::jsonb);
  v_first text := nullif(trim(coalesce(meta ->> 'first_name', meta ->> 'given_name', '')), '');
  v_last text := nullif(trim(coalesce(meta ->> 'last_name', meta ->> 'family_name', '')), '');
  v_full text := nullif(trim(coalesce(meta ->> 'full_name', meta ->> 'name', '')), '');
  v_locale text := case when meta ->> 'locale' in ('es', 'en') then meta ->> 'locale' else 'es' end;
  v_trial integer;
begin
  if v_first is null and v_full is not null then
    v_first := split_part(v_full, ' ', 1);
    v_last := coalesce(v_last, nullif(trim(substr(v_full, char_length(v_first) + 1)), ''));
  end if;

  insert into public.profiles (id, email, first_name, last_name, locale)
  values (new.id, coalesce(new.email, ''), left(v_first, 80), left(v_last, 120), v_locale)
  on conflict (id) do nothing;

  select coalesce((value #>> '{}')::integer, 0) into v_trial
  from public.app_settings where key = 'trial_credits';

  if coalesce(v_trial, 0) > 0 then
    insert into public.credit_ledger (user_id, kind, amount, pool, note)
    values (new.id, 'trial_grant', v_trial, 'pack', 'Welcome trial')
    on conflict do nothing;
  end if;
  return new;
end;
$$;

create trigger on_auth_user_created
  after insert on auth.users
  for each row execute function public.handle_new_user();

create or replace function public.handle_user_email_change()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
begin
  if new.email is distinct from old.email then
    update public.profiles set email = coalesce(new.email, '') where id = new.id;
  end if;
  return new;
end;
$$;

create trigger on_auth_user_email_changed
  after update of email on auth.users
  for each row execute function public.handle_user_email_change();

-- ===== 20260923100200_envelopes.sql =====
-- ─────────────────────────────────────────────────────────────────────────────
-- DocuFirma · envelope workflow
-- Every state transition is a single transactional function with row locks
-- (SELECT … FOR UPDATE) so that races (double submit, concurrent signers,
-- cron vs. signer) cannot corrupt state or the credit ledger.
-- All functions are SECURITY DEFINER and executable only by the service role;
-- the app calls them from server code after validating input with zod.
-- ─────────────────────────────────────────────────────────────────────────────

alter table public.envelopes add column all_signed_at timestamptz;

-- Access tokens for signers. Only SHA-256(token) is stored; the plaintext token
-- travels exclusively in the email link. A reminder issues a new token; previous
-- links keep working until the envelope expires. signers.token_hash mirrors the latest.
create table public.signer_access_tokens (
  token_hash text primary key check (token_hash ~ '^[0-9a-f]{64}$'),
  signer_id uuid not null references public.signers (id) on delete cascade,
  expires_at timestamptz not null,
  revoked_at timestamptz,
  created_at timestamptz not null default now()
);

create index signer_access_tokens_signer_idx on public.signer_access_tokens (signer_id);

-- ── Internal helpers ─────────────────────────────────────────────────────────
create or replace function public._log_event(
  p_envelope_id uuid, p_signer_id uuid, p_type public.envelope_event_type,
  p_metadata jsonb default '{}'::jsonb, p_ip inet default null, p_user_agent text default null
)
returns uuid
language sql
security definer
set search_path = ''
as $$
  insert into public.envelope_events (envelope_id, signer_id, type, metadata, ip, user_agent)
  values (p_envelope_id, p_signer_id, p_type, coalesce(p_metadata, '{}'::jsonb), p_ip, left(p_user_agent, 512))
  returning id
$$;

create or replace function public.log_envelope_event(
  p_envelope_id uuid, p_signer_id uuid, p_type public.envelope_event_type,
  p_metadata jsonb default '{}'::jsonb, p_ip inet default null, p_user_agent text default null
)
returns uuid
language sql
security definer
set search_path = ''
as $$
  select public._log_event(p_envelope_id, p_signer_id, p_type, p_metadata, p_ip, p_user_agent)
$$;

-- Release every outstanding reservation of an envelope (non-signed signers).
create or replace function public._release_envelope_credits(p_envelope_id uuid, p_note text)
returns integer
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_count integer := 0;
  s record;
begin
  for s in select id from public.signers where envelope_id = p_envelope_id and status <> 'signed' loop
    if public.release_credit(s.id, p_note) then
      v_count := v_count + 1;
    end if;
  end loop;
  return v_count;
end;
$$;

-- Resolve a token to its signer, locking signer and envelope. Raises on invalid token.
create or replace function public._lock_signer_by_token(p_token_hash text)
returns table (signer_id uuid, envelope_id uuid)
language plpgsql
security definer
set search_path = ''
as $$
declare
  t public.signer_access_tokens;
  v_envelope uuid;
begin
  select * into t from public.signer_access_tokens where token_hash = p_token_hash;
  if not found or t.revoked_at is not null then
    raise exception 'invalid_token' using errcode = 'P0001';
  end if;
  select s.envelope_id into v_envelope from public.signers s where s.id = t.signer_id;
  -- Lock order: envelope first, then signer (same order everywhere to avoid deadlocks).
  perform 1 from public.envelopes e where e.id = v_envelope for update;
  perform 1 from public.signers s where s.id = t.signer_id for update;
  if t.expires_at <= now() then
    raise exception 'token_expired' using errcode = 'P0001';
  end if;
  return query select t.signer_id, v_envelope;
end;
$$;

-- Validates that a signer may act now. Raises a machine-readable error otherwise.
create or replace function public._assert_signer_can_act(p_signer_id uuid)
returns void
language plpgsql
security definer
set search_path = ''
as $$
declare
  s public.signers;
  e public.envelopes;
begin
  select * into s from public.signers where id = p_signer_id;
  select * into e from public.envelopes where id = s.envelope_id;

  if e.status = 'canceled' then raise exception 'envelope_canceled' using errcode = 'P0001'; end if;
  if e.status = 'declined' then raise exception 'envelope_declined' using errcode = 'P0001'; end if;
  if e.status = 'expired' or (e.expires_at is not null and e.expires_at <= now()) then
    raise exception 'envelope_expired' using errcode = 'P0001';
  end if;
  if e.status = 'completed' or s.status = 'signed' then
    raise exception 'already_signed' using errcode = 'P0001';
  end if;
  if s.status = 'declined' then raise exception 'already_declined' using errcode = 'P0001'; end if;
  if e.status not in ('sent', 'viewed') then raise exception 'envelope_not_active' using errcode = 'P0001'; end if;
  if s.status not in ('sent', 'viewed') then raise exception 'not_your_turn' using errcode = 'P0001'; end if;
  if e.sequential and exists (
    select 1 from public.signers o
    where o.envelope_id = e.id and o.order_index < s.order_index and o.status <> 'signed'
  ) then
    raise exception 'not_your_turn' using errcode = 'P0001';
  end if;
end;
$$;

-- ── Send ─────────────────────────────────────────────────────────────────────
-- p_tokens: [{ "signer_id": uuid, "token_hash": hex }] for ALL signers. Only the signers
-- that must be notified now (all, or the first one if sequential) get their token stored;
-- their ids are returned so the caller emails exactly those.
create or replace function public.send_envelope(
  p_envelope_id uuid,
  p_user_id uuid,
  p_tokens jsonb,
  p_verification_code text,
  p_expires_at timestamptz,
  p_sender jsonb default '{}'::jsonb
)
returns jsonb
language plpgsql
security definer
set search_path = ''
as $$
declare
  e public.envelopes;
  v_signer_ids uuid[];
  v_docs integer;
  v_notify uuid[];
  v_first_order integer;
  v_hash text;
  v_id uuid;
begin
  select * into e from public.envelopes where id = p_envelope_id for update;
  if not found or e.user_id is distinct from p_user_id then
    raise exception 'envelope_not_found' using errcode = 'P0002';
  end if;
  if e.status <> 'draft' then
    raise exception 'envelope_not_draft' using errcode = 'P0001';
  end if;
  if p_expires_at <= now() then
    raise exception 'invalid_expiry' using errcode = 'P0001';
  end if;

  select count(*) into v_docs from public.documents where envelope_id = p_envelope_id;
  if v_docs = 0 then raise exception 'no_documents' using errcode = 'P0001'; end if;
  if v_docs > 10 then raise exception 'too_many_documents' using errcode = 'P0001'; end if;

  select array_agg(id order by order_index, created_at) into v_signer_ids
  from public.signers where envelope_id = p_envelope_id;
  if v_signer_ids is null then raise exception 'no_signers' using errcode = 'P0001'; end if;
  if array_length(v_signer_ids, 1) > 10 then raise exception 'too_many_signers' using errcode = 'P0001'; end if;

  -- Every signer needs a token hash in the payload.
  if (select count(distinct (t ->> 'signer_id')) from jsonb_array_elements(p_tokens) t
      where (t ->> 'signer_id')::uuid = any (v_signer_ids)) <> array_length(v_signer_ids, 1) then
    raise exception 'tokens_mismatch' using errcode = 'P0001';
  end if;

  perform public.reserve_credits(p_user_id, p_envelope_id, v_signer_ids);

  select min(order_index) into v_first_order from public.signers where envelope_id = p_envelope_id;
  if e.sequential then
    select array_agg(id) into v_notify from (
      select id from public.signers where envelope_id = p_envelope_id
      order by order_index, created_at limit 1
    ) f;
  else
    v_notify := v_signer_ids;
  end if;

  foreach v_id in array v_notify loop
    select t ->> 'token_hash' into v_hash from jsonb_array_elements(p_tokens) t
    where (t ->> 'signer_id')::uuid = v_id;
    insert into public.signer_access_tokens (token_hash, signer_id, expires_at)
    values (v_hash, v_id, p_expires_at);
    update public.signers
      set status = 'sent', sent_at = now(), token_hash = v_hash, token_expires_at = p_expires_at
      where id = v_id;
  end loop;

  update public.envelopes set
    status = 'sent',
    sent_at = now(),
    expires_at = p_expires_at,
    verification_code = p_verification_code,
    sender_name = nullif(p_sender ->> 'name', ''),
    sender_email = nullif(p_sender ->> 'email', ''),
    sender_company = nullif(p_sender ->> 'company', '')
  where id = p_envelope_id;

  perform public._log_event(p_envelope_id, null, 'sent',
    jsonb_build_object('signers', array_length(v_signer_ids, 1), 'sequential', e.sequential));

  return jsonb_build_object('notify', to_jsonb(v_notify), 'signers', to_jsonb(v_signer_ids));
end;
$$;

-- Issue (or rotate) the access token of a signer: next sequential signer or reminder.
create or replace function public.issue_signer_token(p_signer_id uuid, p_token_hash text)
returns void
language plpgsql
security definer
set search_path = ''
as $$
declare
  s public.signers;
  e public.envelopes;
begin
  select * into s from public.signers where id = p_signer_id for update;
  select * into e from public.envelopes where id = s.envelope_id;
  if e.status not in ('sent', 'viewed') or s.status in ('signed', 'declined') then
    raise exception 'signer_not_active' using errcode = 'P0001';
  end if;
  insert into public.signer_access_tokens (token_hash, signer_id, expires_at)
  values (p_token_hash, p_signer_id, e.expires_at);
  update public.signers set
    token_hash = p_token_hash,
    token_expires_at = e.expires_at,
    status = case when status = 'pending' then 'sent'::public.signer_status else status end,
    sent_at = coalesce(sent_at, now())
  where id = p_signer_id;
end;
$$;

create or replace function public.record_reminder(p_signer_id uuid, p_resend_id text default null)
returns void
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_envelope uuid;
begin
  update public.signers set reminder_count = reminder_count + 1, last_reminder_at = now()
  where id = p_signer_id returning envelope_id into v_envelope;
  perform public._log_event(v_envelope, p_signer_id, 'reminder_sent',
    jsonb_strip_nulls(jsonb_build_object('resend_id', p_resend_id)));
end;
$$;

-- ── Signer opens the link ────────────────────────────────────────────────────
create or replace function public.mark_signer_viewed(p_token_hash text, p_ip inet default null, p_user_agent text default null)
returns jsonb
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_signer uuid;
  v_envelope uuid;
  s public.signers;
  v_first boolean := false;
begin
  select l.signer_id, l.envelope_id into v_signer, v_envelope from public._lock_signer_by_token(p_token_hash) l;
  perform public._assert_signer_can_act(v_signer);
  select * into s from public.signers where id = v_signer;

  if s.status = 'sent' then
    update public.signers set status = 'viewed', viewed_at = now() where id = v_signer;
    update public.envelopes set status = 'viewed' where id = v_envelope and status = 'sent';
    v_first := true;
  end if;

  perform public._log_event(v_envelope, v_signer, 'opened', jsonb_build_object('first', v_first), p_ip, p_user_agent);
  return jsonb_build_object('signer_id', v_signer, 'envelope_id', v_envelope, 'first_view', v_first);
end;
$$;

-- document_viewed / scrolled_to_end from the signer view.
create or replace function public.record_signer_event(
  p_token_hash text, p_type public.envelope_event_type, p_metadata jsonb default '{}'::jsonb,
  p_ip inet default null, p_user_agent text default null
)
returns void
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_signer uuid;
  v_envelope uuid;
begin
  if p_type not in ('document_viewed', 'scrolled_to_end', 'downloaded') then
    raise exception 'event_not_allowed' using errcode = 'P0001';
  end if;
  select l.signer_id, l.envelope_id into v_signer, v_envelope from public._lock_signer_by_token(p_token_hash) l;
  perform public._log_event(v_envelope, v_signer, p_type, p_metadata, p_ip, p_user_agent);
end;
$$;

-- ── Sign ─────────────────────────────────────────────────────────────────────
-- p_evidence: signature_evidence columns as JSON (paths already uploaded to Storage).
create or replace function public.complete_signature(
  p_token_hash text,
  p_evidence jsonb,
  p_consent_version text,
  p_ip inet default null,
  p_user_agent text default null
)
returns jsonb
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_signer uuid;
  v_envelope uuid;
  e public.envelopes;
  s public.signers;
  v_next uuid;
  v_all_signed boolean;
begin
  select l.signer_id, l.envelope_id into v_signer, v_envelope from public._lock_signer_by_token(p_token_hash) l;
  perform public._assert_signer_can_act(v_signer);
  select * into s from public.signers where id = v_signer;

  insert into public.signature_evidence (
    signer_id, envelope_id, biometric_data_path, biometric_sha256, biometric_key_id,
    signature_image_path, signature_image_sha256, stroke_count, duration_ms, points_count,
    device_type, user_agent, ip, geo_country, geo_region, geo_city, screen_w, screen_h,
    pointer_type, pressure_supported, timezone, client_time, consent_text_version
  ) values (
    v_signer, v_envelope,
    p_evidence ->> 'biometric_data_path',
    p_evidence ->> 'biometric_sha256',
    p_evidence ->> 'biometric_key_id',
    p_evidence ->> 'signature_image_path',
    p_evidence ->> 'signature_image_sha256',
    (p_evidence ->> 'stroke_count')::integer,
    (p_evidence ->> 'duration_ms')::integer,
    (p_evidence ->> 'points_count')::integer,
    p_evidence ->> 'device_type',
    left(p_user_agent, 512),
    p_ip,
    p_evidence ->> 'geo_country',
    p_evidence ->> 'geo_region',
    p_evidence ->> 'geo_city',
    (p_evidence ->> 'screen_w')::integer,
    (p_evidence ->> 'screen_h')::integer,
    p_evidence ->> 'pointer_type',
    coalesce((p_evidence ->> 'pressure_supported')::boolean, false),
    p_evidence ->> 'timezone',
    (p_evidence ->> 'client_time')::timestamptz,
    p_consent_version
  );

  update public.signers set
    status = 'signed',
    signed_at = now(),
    viewed_at = coalesce(viewed_at, now()),
    consent_accepted_at = now(),
    consent_text_version = p_consent_version
  where id = v_signer;

  perform public._log_event(v_envelope, v_signer, 'consent_accepted',
    jsonb_build_object('version', p_consent_version), p_ip, p_user_agent);
  perform public._log_event(v_envelope, v_signer, 'signed',
    jsonb_build_object('biometric_sha256', p_evidence ->> 'biometric_sha256'), p_ip, p_user_agent);
  perform public.consume_credit(v_signer);

  select not exists (select 1 from public.signers where envelope_id = v_envelope and status <> 'signed')
    into v_all_signed;

  select * into e from public.envelopes where id = v_envelope;
  if v_all_signed then
    update public.envelopes set all_signed_at = now(), status = 'viewed' where id = v_envelope;
    insert into public.jobs (type, payload, dedupe_key)
    values ('close_envelope', jsonb_build_object('envelope_id', v_envelope), 'close_envelope:' || v_envelope)
    on conflict (dedupe_key) do nothing;
  elsif e.sequential then
    select id into v_next from public.signers
    where envelope_id = v_envelope and status = 'pending'
    order by order_index, created_at limit 1;
  end if;

  return jsonb_build_object(
    'signer_id', v_signer,
    'envelope_id', v_envelope,
    'all_signed', v_all_signed,
    'next_signer_id', v_next
  );
end;
$$;

-- ── Decline ──────────────────────────────────────────────────────────────────
create or replace function public.decline_signature(
  p_token_hash text, p_reason text default null, p_ip inet default null, p_user_agent text default null
)
returns jsonb
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_signer uuid;
  v_envelope uuid;
  v_released integer;
begin
  select l.signer_id, l.envelope_id into v_signer, v_envelope from public._lock_signer_by_token(p_token_hash) l;
  perform public._assert_signer_can_act(v_signer);

  update public.signers set status = 'declined', declined_at = now(), decline_reason = nullif(left(trim(p_reason), 1000), '')
  where id = v_signer;
  update public.envelopes set status = 'declined', declined_at = now() where id = v_envelope;
  v_released := public._release_envelope_credits(v_envelope, 'declined');
  perform public._log_event(v_envelope, v_signer, 'declined',
    jsonb_build_object('released_credits', v_released), p_ip, p_user_agent);

  return jsonb_build_object('signer_id', v_signer, 'envelope_id', v_envelope, 'released', v_released);
end;
$$;

-- ── Sender actions ───────────────────────────────────────────────────────────
create or replace function public.cancel_envelope(p_envelope_id uuid, p_user_id uuid)
returns jsonb
language plpgsql
security definer
set search_path = ''
as $$
declare
  e public.envelopes;
  v_released integer;
begin
  select * into e from public.envelopes where id = p_envelope_id for update;
  if not found or e.user_id is distinct from p_user_id then
    raise exception 'envelope_not_found' using errcode = 'P0002';
  end if;
  if e.status not in ('sent', 'viewed') or e.all_signed_at is not null then
    raise exception 'envelope_not_cancelable' using errcode = 'P0001';
  end if;
  update public.envelopes set status = 'canceled', canceled_at = now() where id = p_envelope_id;
  update public.signer_access_tokens t set revoked_at = now()
    from public.signers s where s.id = t.signer_id and s.envelope_id = p_envelope_id and t.revoked_at is null;
  v_released := public._release_envelope_credits(p_envelope_id, 'canceled');
  perform public._log_event(p_envelope_id, null, 'canceled', jsonb_build_object('released_credits', v_released));
  return jsonb_build_object('released', v_released);
end;
$$;

create or replace function public.delete_draft_envelope(p_envelope_id uuid, p_user_id uuid)
returns void
language plpgsql
security definer
set search_path = ''
as $$
declare
  e public.envelopes;
begin
  select * into e from public.envelopes where id = p_envelope_id for update;
  if not found or e.user_id is distinct from p_user_id then
    raise exception 'envelope_not_found' using errcode = 'P0002';
  end if;
  if e.status <> 'draft' then
    raise exception 'envelope_not_draft' using errcode = 'P0001';
  end if;
  perform set_config('docufirma.allow_purge', 'on', true);
  delete from public.envelopes where id = p_envelope_id;
end;
$$;

-- Envelope closure finished (signed PDFs + evidence generated).
create or replace function public.mark_envelope_completed(p_envelope_id uuid)
returns boolean
language plpgsql
security definer
set search_path = ''
as $$
declare
  e public.envelopes;
begin
  select * into e from public.envelopes where id = p_envelope_id for update;
  if e.status = 'completed' then
    return false;
  end if;
  if e.all_signed_at is null then
    raise exception 'not_all_signed' using errcode = 'P0001';
  end if;
  update public.envelopes set status = 'completed', completed_at = now() where id = p_envelope_id;
  perform public._log_event(p_envelope_id, null, 'completed', '{}'::jsonb);
  return true;
end;
$$;

-- ── Cron: expiration ─────────────────────────────────────────────────────────
create or replace function public.expire_due_envelopes(p_limit integer default 100)
returns table (envelope_id uuid, released integer)
language plpgsql
security definer
set search_path = ''
as $$
declare
  e record;
  v_released integer;
begin
  for e in
    select id from public.envelopes
    where status in ('sent', 'viewed') and expires_at <= now() and all_signed_at is null
    order by expires_at
    limit p_limit
    for update skip locked
  loop
    update public.envelopes set status = 'expired', expired_at = now() where id = e.id;
    v_released := public._release_envelope_credits(e.id, 'expired');
    perform public._log_event(e.id, null, 'expired', jsonb_build_object('released_credits', v_released));
    envelope_id := e.id;
    released := v_released;
    return next;
  end loop;
end;
$$;

-- ── Account deletion (GDPR art. 17) ──────────────────────────────────────────
-- Deletes personal data and everything not needed for legal defence. Completed
-- envelopes are detached from the account and kept until the retention period ends
-- (art. 17.3.e GDPR: establishment, exercise or defence of legal claims).
-- Returns the storage paths the caller must delete.
create or replace function public.delete_user_account(p_user_id uuid)
returns jsonb
language plpgsql
security definer
set search_path = ''
as $$
declare
  p public.profiles;
  v_paths jsonb;
begin
  select * into p from public.profiles where id = p_user_id for update;
  if not found then
    return jsonb_build_object('paths', '[]'::jsonb);
  end if;

  perform set_config('docufirma.allow_purge', 'on', true);
  perform set_config('docufirma.allow_event_anonymization', 'on', true);

  -- Storage objects of envelopes that are deleted (non-completed).
  select coalesce(jsonb_agg(path), '[]'::jsonb) into v_paths from (
    select 'originals/' || d.original_path as path
      from public.documents d join public.envelopes e on e.id = d.envelope_id
      where e.user_id = p_user_id and e.status <> 'completed'
    union all
    select 'evidence/' || se.biometric_data_path
      from public.signature_evidence se join public.envelopes e on e.id = se.envelope_id
      where e.user_id = p_user_id and e.status <> 'completed' and se.biometric_data_path is not null
    union all
    select 'evidence/' || se.signature_image_path
      from public.signature_evidence se join public.envelopes e on e.id = se.envelope_id
      where e.user_id = p_user_id and e.status <> 'completed' and se.signature_image_path is not null
    union all
    select 'branding/' || p.logo_path where p.logo_path is not null
  ) x;

  delete from public.envelopes where user_id = p_user_id and status <> 'completed';

  -- Sender-side events of retained envelopes lose their network identifiers.
  update public.envelope_events ev set ip = null, user_agent = null
    from public.envelopes e
    where e.id = ev.envelope_id and e.user_id = p_user_id and ev.signer_id is null;

  update public.envelopes set sender_email = null where user_id = p_user_id;

  insert into public.deleted_accounts (user_id, email_sha256, stripe_customer_id)
  values (p_user_id, encode(extensions.digest(lower(p.email), 'sha256'), 'hex'), p.stripe_customer_id);

  delete from public.credit_ledger where user_id = p_user_id;
  delete from public.profiles where id = p_user_id; -- cascades contacts, subscriptions; envelopes.user_id -> null

  return jsonb_build_object('paths', v_paths);
end;
$$;

-- ===== 20260923100300_jobs_ratelimit.sql =====
-- ─────────────────────────────────────────────────────────────────────────────
-- DocuFirma · job queue + rate limiting helpers (service role only)
-- ─────────────────────────────────────────────────────────────────────────────

create or replace function public.enqueue_job(
  p_type text, p_payload jsonb, p_run_at timestamptz default now(), p_dedupe_key text default null,
  p_max_attempts integer default 6
)
returns uuid
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_id uuid;
begin
  insert into public.jobs (type, payload, run_at, dedupe_key, max_attempts)
  values (p_type, coalesce(p_payload, '{}'::jsonb), p_run_at, p_dedupe_key, p_max_attempts)
  on conflict (dedupe_key) do update
    set run_at = least(public.jobs.run_at, excluded.run_at),
        status = case when public.jobs.status = 'failed' then 'pending'::public.job_status else public.jobs.status end
  returning id into v_id;
  return v_id;
end;
$$;

-- Claims due jobs atomically. Jobs stuck in "running" for more than 10 minutes
-- (crashed worker) are reclaimed.
create or replace function public.claim_jobs(p_type text, p_limit integer default 10)
returns setof public.jobs
language sql
security definer
set search_path = ''
as $$
  update public.jobs j set status = 'running', locked_at = now(), attempts = j.attempts + 1
  where j.id in (
    select id from public.jobs
    where type = p_type
      and run_at <= now()
      and (status = 'pending' or (status = 'running' and locked_at < now() - interval '10 minutes'))
    order by run_at
    limit p_limit
    for update skip locked
  )
  returning j.*
$$;

create or replace function public.complete_job(p_job_id uuid)
returns void
language sql
security definer
set search_path = ''
as $$
  update public.jobs set status = 'done', locked_at = null, last_error = null where id = p_job_id
$$;

-- Marks a failed attempt. With p_retry_at the job is rescheduled, otherwise (or when
-- max_attempts is reached) it is marked as failed permanently.
create or replace function public.fail_job(p_job_id uuid, p_error text, p_retry_at timestamptz default null)
returns public.job_status
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_status public.job_status;
begin
  update public.jobs set
    status = case when p_retry_at is not null and attempts < max_attempts then 'pending'::public.job_status else 'failed'::public.job_status end,
    run_at = coalesce(p_retry_at, run_at),
    locked_at = null,
    last_error = left(p_error, 2000)
  where id = p_job_id
  returning status into v_status;
  return v_status;
end;
$$;

-- Fixed-window rate limiter. Returns whether the hit is allowed.
create or replace function public.rate_limit_hit(p_key text, p_limit integer, p_window_seconds integer)
returns table (allowed boolean, remaining integer, reset_at timestamptz)
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_window timestamptz := to_timestamp(floor(extract(epoch from now()) / p_window_seconds) * p_window_seconds);
  v_hits integer;
begin
  insert into public.rate_limits (key, window_start, hits) values (p_key, v_window, 1)
  on conflict (key, window_start) do update set hits = public.rate_limits.hits + 1
  returning hits into v_hits;

  -- Opportunistic cleanup of old windows.
  if random() < 0.01 then
    delete from public.rate_limits where window_start < now() - interval '1 day';
  end if;

  allowed := v_hits <= p_limit;
  remaining := greatest(p_limit - v_hits, 0);
  reset_at := v_window + make_interval(secs => p_window_seconds);
  return next;
end;
$$;

-- ===== 20260923100400_storage.sql =====
-- ─────────────────────────────────────────────────────────────────────────────
-- DocuFirma · Storage buckets (all private)
-- Object paths: {user_id}/{envelope_id}/… (branding: {user_id}/logo.{ext})
-- No client policies: uploads use signed upload URLs created by the server and
-- downloads use short-lived signed URLs created after an authorisation check.
-- ─────────────────────────────────────────────────────────────────────────────

insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types) values
  ('originals', 'originals', false, 26214400, array[
    'application/pdf', 'image/png', 'image/jpeg', 'image/webp',
    'application/vnd.openxmlformats-officedocument.wordprocessingml.document'
  ]),
  ('signed', 'signed', false, 52428800, array['application/pdf']),
  ('evidence', 'evidence', false, 10485760, array['application/octet-stream', 'image/png', 'application/pdf']),
  ('tsa', 'tsa', false, 1048576, array['application/timestamp-query', 'application/timestamp-reply', 'application/octet-stream']),
  ('branding', 'branding', false, 1048576, array['image/png', 'image/jpeg', 'image/webp'])
on conflict (id) do update set
  public = excluded.public,
  file_size_limit = excluded.file_size_limit,
  allowed_mime_types = excluded.allowed_mime_types;

-- ===== 20260923100500_rls.sql =====
-- ─────────────────────────────────────────────────────────────────────────────
-- DocuFirma · Row Level Security and privileges
-- Browser clients (anon / authenticated) only ever see their own data.
-- The signer view never uses user RLS: it goes through server code with the
-- service role after validating the token.
-- ─────────────────────────────────────────────────────────────────────────────

-- Enable RLS everywhere.
alter table public.app_settings enable row level security;
alter table public.profiles enable row level security;
alter table public.subscriptions enable row level security;
alter table public.credit_packs enable row level security;
alter table public.credit_ledger enable row level security;
alter table public.envelopes enable row level security;
alter table public.documents enable row level security;
alter table public.signers enable row level security;
alter table public.signer_access_tokens enable row level security;
alter table public.signature_evidence enable row level security;
alter table public.signed_documents enable row level security;
alter table public.envelope_events enable row level security;
alter table public.contacts enable row level security;
alter table public.stripe_events enable row level security;
alter table public.jobs enable row level security;
alter table public.rate_limits enable row level security;
alter table public.deleted_accounts enable row level security;

-- Defence in depth: remove the blanket grants Supabase gives to API roles,
-- then grant back only what each role needs.
revoke all on all tables in schema public from anon, authenticated;
revoke all on all functions in schema public from public, anon, authenticated;
revoke all on all sequences in schema public from anon, authenticated;

grant all on all tables in schema public to service_role;
grant execute on all functions in schema public to service_role;

-- Owner helper used by child-table policies.
create or replace function public.owns_envelope(p_envelope_id uuid)
returns boolean
language sql
stable
security definer
set search_path = ''
as $$
  select exists (
    select 1 from public.envelopes e where e.id = p_envelope_id and e.user_id = auth.uid()
  )
$$;

create or replace function public.owns_draft_envelope(p_envelope_id uuid)
returns boolean
language sql
stable
security definer
set search_path = ''
as $$
  select exists (
    select 1 from public.envelopes e
    where e.id = p_envelope_id and e.user_id = auth.uid() and e.status = 'draft'
  )
$$;

grant execute on function public.owns_envelope(uuid), public.owns_draft_envelope(uuid) to authenticated;
grant execute on function public.get_available_credits(uuid) to authenticated;

-- ── profiles ─────────────────────────────────────────────────────────────────
grant select on public.profiles to authenticated;
grant update (first_name, last_name, company_name, tax_id, locale, onboarding_completed,
              notify_on_view, notify_on_complete, notify_marketing)
  on public.profiles to authenticated;

create policy profiles_select_own on public.profiles
  for select to authenticated using (id = (select auth.uid()));
create policy profiles_update_own on public.profiles
  for update to authenticated using (id = (select auth.uid())) with check (id = (select auth.uid()));

-- ── subscriptions / credit ledger (read-only for owners) ─────────────────────
grant select on public.subscriptions, public.credit_ledger to authenticated;

create policy subscriptions_select_own on public.subscriptions
  for select to authenticated using (user_id = (select auth.uid()));
create policy credit_ledger_select_own on public.credit_ledger
  for select to authenticated using (user_id = (select auth.uid()));

-- ── credit packs: public catalog of active packs ─────────────────────────────
grant select on public.credit_packs to anon, authenticated;
create policy credit_packs_select_active on public.credit_packs
  for select to anon, authenticated using (active);

-- ── envelopes ────────────────────────────────────────────────────────────────
grant select on public.envelopes to authenticated;
grant insert (title, message, locale, sequential, reminder_days, expires_at) on public.envelopes to authenticated;
grant update (title, message, locale, sequential, reminder_days, expires_at) on public.envelopes to authenticated;

create policy envelopes_select_own on public.envelopes
  for select to authenticated using (user_id = (select auth.uid()));
-- user_id defaults to the caller; drafts only.
create policy envelopes_insert_own on public.envelopes
  for insert to authenticated with check (user_id = (select auth.uid()) and status = 'draft');
create policy envelopes_update_own_draft on public.envelopes
  for update to authenticated
  using (user_id = (select auth.uid()) and status = 'draft')
  with check (user_id = (select auth.uid()) and status = 'draft');

alter table public.envelopes alter column user_id set default auth.uid();

-- ── documents / signers (children of an envelope) ───────────────────────────
grant select on public.documents to authenticated;
grant update (name, order_index) on public.documents to authenticated;
grant delete on public.documents to authenticated;

create policy documents_select_own on public.documents
  for select to authenticated using (public.owns_envelope(envelope_id));
create policy documents_update_own_draft on public.documents
  for update to authenticated
  using (public.owns_draft_envelope(envelope_id)) with check (public.owns_draft_envelope(envelope_id));
create policy documents_delete_own_draft on public.documents
  for delete to authenticated using (public.owns_draft_envelope(envelope_id));

-- signers: token_hash / token_expires_at are never exposed to browsers.
grant select (id, envelope_id, first_name, last_name, email, order_index, status, sent_at, viewed_at,
              signed_at, declined_at, decline_reason, reminder_count, last_reminder_at,
              created_at, updated_at)
  on public.signers to authenticated;
grant insert (envelope_id, first_name, last_name, email, order_index) on public.signers to authenticated;
grant update (first_name, last_name, email, order_index) on public.signers to authenticated;
grant delete on public.signers to authenticated;

create policy signers_select_own on public.signers
  for select to authenticated using (public.owns_envelope(envelope_id));
create policy signers_insert_own_draft on public.signers
  for insert to authenticated with check (public.owns_draft_envelope(envelope_id));
create policy signers_update_own_draft on public.signers
  for update to authenticated
  using (public.owns_draft_envelope(envelope_id)) with check (public.owns_draft_envelope(envelope_id));
create policy signers_delete_own_draft on public.signers
  for delete to authenticated using (public.owns_draft_envelope(envelope_id));

-- ── signed documents / events (read-only for owners) ─────────────────────────
grant select on public.signed_documents, public.envelope_events to authenticated;

create policy signed_documents_select_own on public.signed_documents
  for select to authenticated using (public.owns_envelope(envelope_id));
create policy envelope_events_select_own on public.envelope_events
  for select to authenticated using (public.owns_envelope(envelope_id));

-- ── contacts ─────────────────────────────────────────────────────────────────
grant select, delete on public.contacts to authenticated;
grant insert (first_name, last_name, email) on public.contacts to authenticated;
grant update (first_name, last_name, email) on public.contacts to authenticated;

alter table public.contacts alter column user_id set default auth.uid();

create policy contacts_select_own on public.contacts
  for select to authenticated using (user_id = (select auth.uid()));
create policy contacts_insert_own on public.contacts
  for insert to authenticated with check (user_id = (select auth.uid()));
create policy contacts_update_own on public.contacts
  for update to authenticated using (user_id = (select auth.uid())) with check (user_id = (select auth.uid()));
create policy contacts_delete_own on public.contacts
  for delete to authenticated using (user_id = (select auth.uid()));

-- ── service-role-only tables: RLS on, no policies ────────────────────────────
-- app_settings, signer_access_tokens, signature_evidence, stripe_events, jobs,
-- rate_limits, deleted_accounts. (Nothing granted to anon/authenticated.)

-- New objects created later in public must not leak to API roles by default.
alter default privileges in schema public revoke all on tables from anon, authenticated;
alter default privileges in schema public revoke all on functions from public, anon, authenticated;
alter default privileges in schema public revoke all on sequences from anon, authenticated;

-- ===== 20260923100600_catalog.sql =====
-- Default credit packs catalog (production data). `pnpm stripe:setup` fills stripe_price_id.
insert into public.credit_packs (slug, name_es, name_en, credits, price_cents, currency, sort_order) values
  ('pack-25', 'Pack 25 firmas', '25 signatures pack', 25, 1500, 'eur', 1),
  ('pack-100', 'Pack 100 firmas', '100 signatures pack', 100, 4900, 'eur', 2),
  ('pack-500', 'Pack 500 firmas', '500 signatures pack', 500, 19900, 'eur', 3)
on conflict (slug) do nothing;

-- ===== 20260923100700_envelope_expiry_days.sql =====
-- Draft setting: number of days the signing links stay valid once sent.
-- expires_at is computed from it by send_envelope's caller at send time.
alter table public.envelopes
  add column expiry_days integer not null default 30 check (expiry_days between 1 and 120);

grant insert (expiry_days), update (expiry_days) on public.envelopes to authenticated;

-- ===== 20260923100800_job_claim_by_key.sql =====
-- Claims one specific job (by dedupe key) atomically, so that the inline closure triggered
-- after the last signature and the cron worker never process the same envelope twice.
create or replace function public.claim_job_by_key(p_dedupe_key text)
returns setof public.jobs
language sql
security definer
set search_path = ''
as $$
  update public.jobs j set status = 'running', locked_at = now(), attempts = j.attempts + 1
  where j.id = (
    select id from public.jobs
    where dedupe_key = p_dedupe_key
      and (status in ('pending', 'failed') or (status = 'running' and locked_at < now() - interval '10 minutes'))
    for update skip locked
  )
  returning j.*
$$;

revoke all on function public.claim_job_by_key(text) from public, anon, authenticated;
grant execute on function public.claim_job_by_key(text) to service_role;

-- TSA retry bookkeeping per artifact.
create or replace function public.record_tsa_result(
  p_artifact_id uuid,
  p_granted boolean,
  p_fields jsonb,
  p_error text default null,
  p_next_attempt_at timestamptz default null
)
returns public.signed_documents
language plpgsql
security definer
set search_path = ''
as $$
declare
  r public.signed_documents;
begin
  update public.signed_documents set
    tsa_status = case when p_granted then 'granted'::public.tsa_status else 'failed'::public.tsa_status end,
    tsa_attempts = tsa_attempts + 1,
    tsa_error = case when p_granted then null else left(p_error, 1000) end,
    tsa_next_attempt_at = case when p_granted then null else p_next_attempt_at end,
    tsa_provider = coalesce(p_fields ->> 'provider', tsa_provider),
    tsq_path = coalesce(p_fields ->> 'tsq_path', tsq_path),
    tsr_path = coalesce(p_fields ->> 'tsr_path', tsr_path),
    tsa_serial = coalesce(p_fields ->> 'serial', tsa_serial),
    tsa_gen_time = coalesce((p_fields ->> 'gen_time')::timestamptz, tsa_gen_time),
    tsa_policy_oid = coalesce(p_fields ->> 'policy_oid', tsa_policy_oid),
    tsa_name = coalesce(p_fields ->> 'tsa_name', tsa_name),
    tsa_hash_alg = coalesce(p_fields ->> 'hash_alg', tsa_hash_alg)
  where id = p_artifact_id and tsa_status <> 'granted'
  returning * into r;
  return r;
end;
$$;

revoke all on function public.record_tsa_result(uuid, boolean, jsonb, text, timestamptz) from public, anon, authenticated;
grant execute on function public.record_tsa_result(uuid, boolean, jsonb, text, timestamptz) to service_role;

-- ===== 20260923100900_biometric_retention.sql =====
-- GDPR retention of biometric evidence (docs/LEGAL.md §4): after N years the encrypted stroke
-- data is deleted; its hash, the signature image, the signed PDFs and the evidence certificate remain.
alter table public.signature_evidence add column biometric_purged_at timestamptz;

-- Marks up to p_limit expired rows as purged and returns their storage paths for deletion.
create or replace function public.claim_expired_biometrics(p_years integer, p_limit integer default 200)
returns table (evidence_id uuid, biometric_data_path text)
language sql
security definer
set search_path = ''
as $$
  with target as (
    select id, biometric_data_path as old_path
      from public.signature_evidence
     where biometric_data_path is not null
       and server_time < now() - make_interval(years => p_years)
     order by server_time
     limit p_limit
     for update skip locked
  ), purged as (
    update public.signature_evidence se
       set biometric_purged_at = now(), biometric_data_path = null
      from target
     where se.id = target.id
    returning se.id, target.old_path
  )
  select id, old_path from purged
$$;

revoke all on function public.claim_expired_biometrics(integer, integer) from public, anon, authenticated;
grant execute on function public.claim_expired_biometrics(integer, integer) to service_role;

-- ===== 20260923101000_scheduled_jobs.sql =====
-- Scheduled jobs run by Supabase (pg_cron + pg_net) instead of Vercel Cron (D-036).
-- Each job calls the app's /api/cron/* endpoint with `Authorization: Bearer <CRON_SECRET>`.
-- The URL and the secret live in Supabase Vault (never in migrations). Once per project:
--
--   select vault.create_secret('https://docufirma.es', 'app_url');
--   select vault.create_secret('<same value as CRON_SECRET in Vercel>', 'cron_secret');
--
-- Databases without pg_cron/pg_net (the bare Postgres used by `pnpm test:db` / `pnpm stack:up`)
-- skip this migration with a notice.

do $migration$
begin
  if not exists (select 1 from pg_available_extensions where name = 'pg_cron')
    or not exists (select 1 from pg_available_extensions where name = 'pg_net') then
    raise notice 'pg_cron/pg_net not available: scheduled jobs not installed';
    return;
  end if;

  create extension if not exists pg_cron;
  create extension if not exists pg_net;

  -- Fires an async GET (pg_net queues it; the cron worker never waits for the response).
  create or replace function public.invoke_app_cron(p_path text)
  returns bigint
  language plpgsql
  security definer
  set search_path = ''
  as $fn$
  declare
    v_url text;
    v_secret text;
  begin
    select decrypted_secret into v_url from vault.decrypted_secrets where name = 'app_url';
    select decrypted_secret into v_secret from vault.decrypted_secrets where name = 'cron_secret';
    if v_url is null or v_secret is null then
      raise warning 'invoke_app_cron(%): create the Vault secrets app_url and cron_secret', p_path;
      return null;
    end if;
    return net.http_get(
      url := rtrim(v_url, '/') || p_path,
      headers := jsonb_build_object('Authorization', 'Bearer ' || v_secret),
      timeout_milliseconds := 60000
    );
  end;
  $fn$;

  revoke all on function public.invoke_app_cron(text) from public, anon, authenticated, service_role;

  -- (Re)schedule by name so the migration is idempotent. Times are UTC.
  perform cron.unschedule(jobname)
  from cron.job
  where jobname in ('docufirma-reminders', 'docufirma-expire', 'docufirma-retry-tsa', 'docufirma-retention');

  perform cron.schedule('docufirma-reminders', '0 * * * *', $$select public.invoke_app_cron('/api/cron/reminders')$$);
  perform cron.schedule('docufirma-expire', '15 * * * *', $$select public.invoke_app_cron('/api/cron/expire')$$);
  perform cron.schedule('docufirma-retry-tsa', '*/5 * * * *', $$select public.invoke_app_cron('/api/cron/retry-tsa')$$);
  perform cron.schedule('docufirma-retention', '30 3 * * *', $$select public.invoke_app_cron('/api/cron/retention')$$);
end
$migration$;

-- ===== 20260923101100_provision_user.sql =====
-- Idempotent user provisioning (profile + trial credits), shared by the sign-up trigger and the
-- app. A user created before the schema existed (or whose trigger failed) has no profile; the app
-- now calls provision_user() instead of redirecting, which previously caused a redirect loop.

create or replace function public.provision_user(p_user_id uuid)
returns public.profiles
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_user record;
  meta jsonb;
  v_first text;
  v_last text;
  v_full text;
  v_locale text;
  v_trial integer;
  v_profile public.profiles;
begin
  select id, email, raw_user_meta_data into v_user from auth.users where id = p_user_id;
  if not found then
    raise exception 'user % not found', p_user_id using errcode = 'P0002';
  end if;

  meta := coalesce(v_user.raw_user_meta_data, '{}'::jsonb);
  v_first := nullif(trim(coalesce(meta ->> 'first_name', meta ->> 'given_name', '')), '');
  v_last := nullif(trim(coalesce(meta ->> 'last_name', meta ->> 'family_name', '')), '');
  v_full := nullif(trim(coalesce(meta ->> 'full_name', meta ->> 'name', '')), '');
  v_locale := case when meta ->> 'locale' in ('es', 'en') then meta ->> 'locale' else 'es' end;

  if v_first is null and v_full is not null then
    v_first := split_part(v_full, ' ', 1);
    v_last := coalesce(v_last, nullif(trim(substr(v_full, char_length(v_first) + 1)), ''));
  end if;

  insert into public.profiles (id, email, first_name, last_name, locale)
  values (v_user.id, coalesce(v_user.email, ''), left(v_first, 80), left(v_last, 120), v_locale)
  on conflict (id) do nothing;

  select coalesce((value #>> '{}')::integer, 0) into v_trial
  from public.app_settings where key = 'trial_credits';

  if coalesce(v_trial, 0) > 0 then
    insert into public.credit_ledger (user_id, kind, amount, pool, note)
    values (v_user.id, 'trial_grant', v_trial, 'pack', 'Welcome trial')
    on conflict do nothing;
  end if;

  select * into v_profile from public.profiles where id = p_user_id;
  return v_profile;
end;
$$;

revoke all on function public.provision_user(uuid) from public, anon, authenticated;
grant execute on function public.provision_user(uuid) to service_role;

create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
begin
  perform public.provision_user(new.id);
  return new;
end;
$$;

-- Backfill users that signed up before the schema was applied.
select public.provision_user(u.id)
from auth.users u
where not exists (select 1 from public.profiles p where p.id = u.id);

-- Make PostgREST pick up the new function signature right away.
notify pgrst, 'reload schema';

-- Record the migrations as applied so a later `supabase db push` does not re-run them.
create schema if not exists supabase_migrations;
create table if not exists supabase_migrations.schema_migrations (version text primary key, statements text[], name text);
insert into supabase_migrations.schema_migrations (version, name, statements) values ('20260923100000', 'init_schema', '{}') on conflict (version) do nothing;
insert into supabase_migrations.schema_migrations (version, name, statements) values ('20260923100100', 'credits', '{}') on conflict (version) do nothing;
insert into supabase_migrations.schema_migrations (version, name, statements) values ('20260923100200', 'envelopes', '{}') on conflict (version) do nothing;
insert into supabase_migrations.schema_migrations (version, name, statements) values ('20260923100300', 'jobs_ratelimit', '{}') on conflict (version) do nothing;
insert into supabase_migrations.schema_migrations (version, name, statements) values ('20260923100400', 'storage', '{}') on conflict (version) do nothing;
insert into supabase_migrations.schema_migrations (version, name, statements) values ('20260923100500', 'rls', '{}') on conflict (version) do nothing;
insert into supabase_migrations.schema_migrations (version, name, statements) values ('20260923100600', 'catalog', '{}') on conflict (version) do nothing;
insert into supabase_migrations.schema_migrations (version, name, statements) values ('20260923100700', 'envelope_expiry_days', '{}') on conflict (version) do nothing;
insert into supabase_migrations.schema_migrations (version, name, statements) values ('20260923100800', 'job_claim_by_key', '{}') on conflict (version) do nothing;
insert into supabase_migrations.schema_migrations (version, name, statements) values ('20260923100900', 'biometric_retention', '{}') on conflict (version) do nothing;
insert into supabase_migrations.schema_migrations (version, name, statements) values ('20260923101000', 'scheduled_jobs', '{}') on conflict (version) do nothing;
insert into supabase_migrations.schema_migrations (version, name, statements) values ('20260923101100', 'provision_user', '{}') on conflict (version) do nothing;
commit;
