/**
 * Bundles every migration in supabase/migrations into one transactional script for the
 * Supabase SQL Editor (for projects set up without the Supabase CLI). It also records the
 * migrations as applied, so a later `supabase db push` does not re-run them.
 *
 *   pnpm db:bundle   →   supabase/dashboard/all-migrations.sql
 */
import { readdirSync, readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";

const root = join(__dirname, "..");
const dir = join(root, "supabase", "migrations");
const files = readdirSync(dir)
  .filter((f) => f.endsWith(".sql"))
  .sort();

const parts = [
  "-- DocuFirma: every migration in supabase/migrations, for the Supabase SQL Editor.",
  "-- GENERATED by `pnpm db:bundle` — do not edit by hand.",
  "-- Runs in one transaction: if anything fails, nothing is applied. Paste it as a whole.",
  "begin;",
];
for (const file of files) {
  parts.push("", `-- ===== ${file} =====`, readFileSync(join(dir, file), "utf8").trimEnd());
}
parts.push(
  "",
  "-- Record the migrations as applied so a later `supabase db push` does not re-run them.",
  "create schema if not exists supabase_migrations;",
  "create table if not exists supabase_migrations.schema_migrations (version text primary key, statements text[], name text);",
);
for (const file of files) {
  const base = file.replace(/\.sql$/, "");
  const [version, ...rest] = base.split("_");
  parts.push(
    `insert into supabase_migrations.schema_migrations (version, name, statements) values ('${version}', '${rest.join("_")}', '{}') on conflict (version) do nothing;`,
  );
}
parts.push("commit;", "");

const out = join(root, "supabase", "dashboard", "all-migrations.sql");
writeFileSync(out, parts.join("\n"));
console.log(`✓ ${files.length} migrations → ${out}`);
